steps:
  - id: 'build NEWEN'
    name: gcr.io/mgh-en/build-new-en
    args: ['bash', './$PROJECT_ID/deploy.sh']
  - id: 'gcloud deploy app'
    name: gcr.io/cloud-builders/gcloud-slim
    dir: deploy/FR
    args: ['--project=$PROJECT_ID', 'app', 'deploy', 'app.yaml', '--quiet']
