steps:
  - id: 'build NEWEN'
    name: gcr.io/$PROJECT_ID/build-$PROJECT_ID
    args: ['./$PROJECT_ID/deploy.sh']
  - id: 'gcloud deploy app'
    name: gcr.io/cloud-builders/gcloud-slim
    dir: deploy/$PROJECT_ID
    args: ['--project=$PROJECT_ID', 'app', 'deploy', 'app.yaml', '--quiet', '--version 1']