# -*- coding: utf-8 -*-
proplists = {"quesada":[],"kyero":[1338],"8-9":[],"0-1":[1338],"las-ramblas":[],"long-term-rental":[],"rocio-del-mar":[],"guardamar-del-segura":[],"los-alcazares":[],"apartment":[1338],"villamartin":[1338],"alameda":[],"orihuela-costa":[1338],"semidetached-villa":[],"la torreta":[],"la-manga":[],"punta-prima":[],"detached-villa":[],"quadhouse":[],"los-dolses":[],"golf":[],"All":[1338],"holiday-rentals":[],"campoamor":[],"beach":[1338],"mar-azul":[],"las-filipinas":[],"algorfa":[],"4-5":[],"torrevieja":[],"commercial":[],"los-altos":[],"villa":[],"1-2":[],"5-6":[],"luxury":[],"3-4":[],"rio-mar":[],"key-ready":[],"7-8":[],"townhouse":[],"los-balcones":[],"miraflores":[],"la-mata":[],"2-3":[],"finca":[],"dream-hills":[],"6-7":[],"penthouse":[],"playa-flamenca":[],"topsix":[],"la-zenia":[],"cabo-roig":[],"9-10":[]}
props={
"1338":{"rental":"False","pid":"1338","created":"2015-11-10 11:27:59.002998",
"pics":["//lh3.googleusercontent.com/-cKRDI2lVvGc/VkCr2dEPVGI/AAAAAAAAJUA/8Zju_Al3Z-U/s0/1.jpg","//lh3.googleusercontent.com/-p-Wear9xJ8c/VkCr2faACMI/AAAAAAAAJT8/gaJzekyvzNo/s0/2.jpg","//lh3.googleusercontent.com/-hAP5zT4fBEw/VkCr2IBrLxI/AAAAAAAAJUU/SxAL-GNDYUs/s0/3.jpg","//lh3.googleusercontent.com/-k9hy30Eio14/VkCr2XijlbI/AAAAAAAAJTo/chWwbZRxg44/s0/4.jpg","//lh3.googleusercontent.com/-zfg_GzYHBl8/VkCr2lv0NTI/AAAAAAAAJT0/-k7ayCvMUmw/s0/5.jpg","//lh3.googleusercontent.com/-5oJ5md3EwZM/VkCr2wQgWVI/AAAAAAAAJUU/df9tqJmwYTg/s0/6.jpg","//lh3.googleusercontent.com/-Mm9th5gtF98/VkCr2ytIpMI/AAAAAAAAJUU/sPMQmWjyHCQ/s0/7.jpg","//lh3.googleusercontent.com/-lkAmybvJPIQ/VkCr3MwrjxI/AAAAAAAAJTk/pIty5IbrQc0/s0/8.jpg","//lh3.googleusercontent.com/-Z6bEnal4_BY/VkCr3SWDeNI/AAAAAAAAJT4/gw0kV5slWbs/s0/9.jpg","//lh3.googleusercontent.com/-nlisaoVqKLw/VkCr3ZbcJdI/AAAAAAAAJTs/MZ6k3ZmQUzY/s0/9a.jpg","//lh3.googleusercontent.com/-QJch5O9GOm8/VkCr3n-c3HI/AAAAAAAAJTw/7LJas3sozfg/s0/9b.jpg"],
"lastedited":"2015-11-10 11:27:59.329141","ref":"AP-VG1234","price":"50000","originalprice":"60000","frequency":"sale","ptype":"Apartment",
"town":"Orihuela Costa","province":"Alicante","location":"Villamartin Golf","beds":"3","baths":"2","pool":"private","description":"A Lovely house for a man and a mouse.",
"DE":"Eine schöne Unterkunft für einen Mann und eine Maus.","FR":"Une belle propriété pour un homme et une souris.","NL":"Een mooie woning voor een man en een muis.","display":"True","offplan":"False","living":"95",
"plot":"0","fireplace":"True","heating":"True","aircon":"False","kitchen":"open","utility":"True",
"solarium":"False","balconies":"20","furnished":"fully","topsix":"False","salestage":"0","beach":"True",
"golf":"False","luxury":"False","finca":"False","penthouse":"False","EUR":""}
}
