rubruns=[
{
"rubrun":"All-props",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND blnrental = 0 ORDER BY intprice ASC",
"description":"Villas, Ferienwohnungen, Stadth&auml;user und Fincas zu verkaufen in Villamartin, Playa Flamenca, Cabo Roig, Los Altos, Los Balcones, Guardamar del Segura, Ciudad Quesada in Torrevieja and  Orihuela Costa areas of Southern Costa Blanca Spanien",
"keywords":"Villamartin Villas, Ferienwohnungen, Stadth&auml;user und Fincas, Playa Flamenca, Cabo Roig, Guardamar del Segura und Ciudad Quesada",
"title":"Villas, Ferienwohnungen, Stadth&auml;user und Fincas zu verkaufen, Playa Flamenca, Cabo Roig, Guardamar del Segura, Ciudad Quesada Costa Blanca Spanien",
"h1":"Immobilien zu verkaufen in Villamartin, Cabo Roig, Torrevieja, Playa Flamenca und Orihuela Costa Spanien",
"pagename_en":"villas-apartments-townhouses-and-fincas-for-sale-",
"pagename_nl":"villas-appartementen-geschakelde-woningen-en-fincas-te-koop-",
"pagename_fr":"Villas-appartements-maisons-mitoyennes-et-fincas-a-vendre-",
"pagename_de":"villas-Ferienwohnungen-Stadthauser-und-fincas-zu-verkaufen-"

},
{
"rubrun":"Up to 100000",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND blnrental = 0 AND intprice <= 100000 ORDER BY intprice ASC",
"description":"Villas, Ferienwohnungen, Stadth&auml;user und spanisch H&auml;user f&uuml;r weniger als &euro;100,000",
"keywords":"Schn&auml;ppchen Villas, Schn&auml;ppchen Ferienwohnungen, Schn&auml;ppchen Costa Blanca Ferienwohnungen und Stadth&auml;user",
"title":"Costa Blanca Immobilien f&uuml;r weniger als &euro;100,000",
"h1":"Immobilien zu verkaufen in Villamartin, Cabo Roig, Torrevieja, Playa Flamenca Costa Blanca S&uuml;d f&uuml;r weniger als &euro;100,000",
"pagename_en":"costa-blanca-property-for-less-than-100000-",
"pagename_nl":"Eigendom-in-de-Costa-Blanca-tot-100000-euro-",
"pagename_fr":"Propriete-a-Costa-Blanca-jusqu-a-100000-euro-",
"pagename_de":"costa-blanca-Immobilien-fur-weniger-als-100000-"
},
{
"rubrun":"101000-200000",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND blnrental = 0 AND intprice >= 101000  AND intprice <= 200000 ORDER BY intprice ASC",
"description":"Villas, Ferienwohnungen, Stadth&auml;user und spanisch H&auml;user zwischen &euro;100,000 und &euro;200,000 preislich",
"keywords":"preiswert Villas, preiswert Ferienwohnungen, Schn&auml;ppchen Preisen Costa Blanca Ferienwohnungen und Stadth&auml;user",
"title":"Costa Blanca Immobilien priced zwischen &euro;100,000 und &euro;200,000",
"h1":"Immobilien zu verkaufen in Villamartin, Cabo Roig, Torrevieja, Playa Flamenca Costa Blanca S&uuml;d zwischen &euro;100,000 und &euro; 200,000 preislich",
"pagename_en":"costa-blanca-property-from-100000-to-200000-",
"pagename_nl":"Eigendom-aan-de-Costa-Blanca-van-100000-tot-200000-euro-",
"pagename_fr":"Propriete-a-Costa-Blanca-de-100000-euro-a-200000-euro-",
"pagename_de":"costa-blanca-Immobilien-von-100000-bis-200000-"
},
{
"rubrun":"201000-300000",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND blnrental = 0 AND intprice >= 201000  AND intprice <= 300000 ORDER BY intprice ASC",
"description":"Villas, Ferienwohnungen, Stadth&auml;user and spanisch H&auml;user zwischen &euro;200,000 und &euro; 300,000 preislich",
"keywords":"w&uuml;nschenswert Villas, Attractive Ferienwohnungen, Wunderbare Costa Blanca H&auml;user",
"title":"Costa Blanca Immobilien zwischen &euro;200,000 und &euro; 300,000 preislich",
"h1":"Immobilien zu verkaufen in Villamartin, Cabo Roig, Torrevieja, Playa Flamenca Costa Blanca S&uuml;d zwischen &euro;200,000 und &euro; 300,000 preislich",
"pagename_en":"costa-blanca-property-from-200000-to-300000-",
"pagename_nl":"Eigendom-aan-de-Costa-Blanca-van-200000-tot-300000-euro-",
"pagename_fr":"Propriete-a-Costa-Blanca-de-200000-euro-a-300000-euro-",
"pagename_de":"costa-blanca-Immobilien-von-200000-bis-300000-"
},
{
"rubrun":"301000-400000",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND blnrental = 0 AND intprice >= 301000  AND intprice <= 400000 ORDER BY intprice ASC",
"description":"Villas, Ferienwohnungen, Stadth&auml;user and spanisch H&auml;user zwischen &euro;300,000 und &euro; 400,000 preislich",
"keywords":"Very nice Villas, Luxury Ferienwohnungen, Costa Blanca H&auml;user for retirement",
"title":"Costa Blanca Immobilien priced zwischen &euro;300,000 und &euro; 400,000",
"h1":"Immobilien zu verkaufen in Villamartin, Cabo Roig, Torrevieja, Playa Flamenca Costa Blanca S&uuml;d zwischen &euro;300,000 und &euro; 400,000 preislich",
"pagename_en":"costa-blanca-property-from-300000-to-400000-",
"pagename_nl":"Eigendom-aan-de-Costa-Blanca-van-300000-tot-400000-euro-",
"pagename_fr":"Propriete-a-Costa-Blanca-de-300000-euro-a-400000-euro-",
"pagename_de":"costa-blanca-Immobilien-von-300000-bis-400000-"
},
{
"rubrun":"401000-500000",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND blnrental = 0 AND intprice >= 401000  AND intprice <= 500000 ORDER BY intprice ASC",
"description":"Ferienwohnungen, Stadth&auml;user und spanische villas zwischen &euro;400,000 und &euro; 500,000 preislich",
"keywords":"Well appointed Ferienwohnungen villas, Costa Blanca H&auml;user for comfortable living",
"title":"Costa Blanca Immobilien priced zwischen &euro;400,000 und &euro; 500,000",
"h1":"Immobilien zu verkaufen in Villamartin, Cabo Roig, Torrevieja, Playa Flamenca Costa Blanca S&uuml;d zwischen &euro;400,000 und &euro; 500,000 preislich",
"pagename_en":"costa-blanca-property-from-400000-to-500000-",
"pagename_nl":"Eigendom-aan-de-Costa-Blanca-van-400000-tot-500000-euro-",
"pagename_fr":"Propriete-a-Costa-Blanca-de-400000-euro-a-500000-euro-",
"pagename_de":"costa-blanca-Immobilien-von-400000-bis-500000-"
},
{
"rubrun":"501000-600000",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND blnrental = 0 AND intprice >= 501000  AND intprice <= 600000 ORDER BY intprice ASC",
"description":"Ferienwohnungen, Stadth&auml;user und spanische villas zwischen &euro;500,000 und &euro; 600,000 preislich",
"keywords":"Costa Blanca H&auml;user, Villas, Ferienwohnungen, Golf H&auml;user, Immobilien Costa Blanca S&uuml;d, Spanien",
"title":"Costa Blanca Immobilien priced zwischen &euro;500,000 und &euro; 600,000",
"h1":"Immobilien zu verkaufen in Villamartin, Cabo Roig, Campoamor, Playa Flamenca Costa Blanca S&uuml;d zwischen &euro;500,000 und &euro; 600,000 preislich",
"pagename_en":"costa-blanca-property-from-500000-to-600000-",
"pagename_nl":"Eigendom-aan-de-Costa-Blanca-van-500000-tot-600000-euro-",
"pagename_fr":"Propriete-a-Costa-Blanca-de-500000-euro-a-600000-euro-",
"pagename_de":"costa-blanca-Immobilien-von-500000-bis-600000-"
},
{
"rubrun":"601000-700000",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND blnrental = 0 AND intprice >= 601000  AND intprice <= 700000 ORDER BY intprice ASC",
"description":"Ferienwohnungen, Stadth&auml;user und spanische villas zwischen &euro;600,000 und &euro; 700,000 preislich",
"keywords":"Costa Blanca H&auml;user, Villas, Ferienwohnungen, Golf H&auml;user, Immobilien Costa Blanca S&uuml;d, Spanien",
"title":"Costa Blanca Immobilien priced zwischen &euro;600,000 und &euro; 700,000",
"h1":"Immobilien zu verkaufen in Villamartin, Cabo Roig, Campoamor, Playa Flamenca Costa Blanca S&uuml;d zwischen &euro;600,000 und &euro; 700,000 preislich",
"pagename_en":"costa-blanca-property-from-600000-to-700000-",
"pagename_nl":"Eigendom-aan-de-Costa-Blanca-van-600000-tot-700000-euro-",
"pagename_fr":"Propriete-a-Costa-Blanca-de-600000-euro-a-700000-euro-",
"pagename_de":"costa-blanca-Immobilien-von-600000-bis-700000-"
},
{
"rubrun":"701000-800000",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND blnrental = 0 AND intprice >= 701000  AND intprice <= 800000 ORDER BY intprice ASC",
"description":"Ferienwohnungen, Stadth&auml;user und spanische villas zwischen &euro;700,000 und &euro; 800,000 preislich",
"keywords":"komfortabel Costa Blanca H&auml;user, Villas, Ferienwohnungen, Golf H&auml;user, Immobilien Costa Blanca S&uuml;d, Spanien",
"title":"Costa Blanca Immobilien priced zwischen &euro;700,000 und &euro; 800,000",
"h1":"Immobilien zu verkaufen in Villamartin, Cabo Roig, Campoamor, Playa Flamenca Costa Blanca S&uuml;d zwischen &euro;700,000 und &euro; 800,000 preislich",
"pagename_en":"costa-blanca-property-from-700000-to-800000-",
"pagename_nl":"Eigendom-aan-de-Costa-Blanca-van-700000-tot-800000-euro-",
"pagename_fr":"Propriete-a-Costa-Blanca-de-700000-euro-a-800000-euro-",
"pagename_de":"costa-blanca-Immobilien-von-700000-bis-800000-"
},
{
"rubrun":"801000-900000",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND blnrental = 0 AND intprice >= 801000  AND intprice <= 900000 ORDER BY intprice ASC",
"description":"Ferienwohnungen, Stadth&auml;user and spanische villas zwischen &euro;800,000 und &euro; 900,000 preislich",
"keywords":"Luxus Costa Blanca H&auml;user, Villas, Ferienwohnungen, Golf H&auml;user, Immobilien Costa Blanca S&uuml;d, Spanien",
"title":"Costa Blanca Immobilien priced zwischen &euro;800,000 und &euro; 900,000",
"h1":"Immobilien zu verkaufen in Villamartin, Cabo Roig, Campoamor, Playa Flamenca Costa Blanca S&uuml;d zwischen &euro;800,000 und &euro; 900,000 preislich",
"pagename_en":"costa-blanca-property-from-800000-to-900000-",
"pagename_nl":"Eigendom-aan-de-Costa-Blanca-van-800000-tot-900000-euro-",
"pagename_fr":"Propriete-a-Costa-Blanca-de-800000-euro-a-900000-euro-",
"pagename_de":"costa-blanca-Immobilien-von-800000-bis-900000-"
},
{
"rubrun":"more than 900000",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND blnrental = 0 AND intprice > 900000 ORDER BY intprice ASC",
"description":"Ferienwohnungen, Stadth&auml;user und spanische villas priced over &euro;900,000",
"keywords":"Unverwechselbar Costa Blanca H&auml;user, Villas, Ferienwohnungen, Golf H&auml;user, Immobilien Costa Blanca S&uuml;d, Spanien",
"title":"Unverwechselbar Costa Blanca Immobilien von &euro;900,000",
"h1":"Immobilien zu verkaufen in Villamartin, Cabo Roig, Campoamor, Playa Flamenca Costa Blanca S&uuml;d Preis mehr als&euro;900,000",
"pagename_en":"costa-blanca-property-from-900000-",
"pagename_nl":"Eigendom-aan-de-Costa-Blanca-vanaf-900000-euro-",
"pagename_fr":"Propriete-a-Costa-Blanca-a-partir-de-900000-euro-",
"pagename_de":"costa-blanca-Immobilien-von-900000-"
},
{
"rubrun":"Commercial",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND (strpropertytype IN ('Bar','Restaurant','Business','Commercial','Hotel')) ORDER BY intprice ASC",
"description":"Business and commercial Immobilien in Costa Blanca S&uuml;d Bars, Restaurants, Hotels",
"keywords":"Commercial Immobilien Costa Blanca, Gesch&auml;ft zum Verkauf Costa Blanca, Bars, Restaurants, Hotels",
"title":"Gewerbeimmobilien Costa Blanca",
"h1":"Gewerbeimmobilien Costa Blanca S&uuml;d",
"pagename_en":"costa-blanca-commercial-property-",
"pagename_nl":"Commerciele-panden-Costa-Blanca-Zuid-",
"pagename_fr":"Batiments-commerciaux-Costa-Blanca-Sud-",
"pagename_de":"costa-blanca-Gewerbeimmobilien-"
},
{
"rubrun":"Long Term Rentals",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND blnrental = 1 AND strFrequency = 'month' ORDER BY intprice ASC",
"description":"Langfristige Vermietungen in Costa Blanca S&uuml;d",
"keywords":"Costa Blanca Vermietung, Langzeitmiete",
"title":"Costa Blanca Immobilien zur Langzeitmiete",
"h1":"Immobilien zur Langzeitmiete Costa Blanca S&uuml;d",
"pagename_en":"costa-blanca-long-term-rental-property-",
"pagename_nl":"Eigendom-te-huur-voor-lange-termijn-costa-blanca-zuid-",
"pagename_fr":"Propriete-a-louer-pour-long-terme-Costa-Blanca-Sud-",
"pagename_de":"costa-blanca-Langfristige-Vermietungen-"
},
{
"rubrun":"Holiday Rentals",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND blnrental = 1 AND strFrequency = 'week' ORDER BY intprice ASC",
"description":"Zu Vermietende Ferienunterk&auml;Nfte in Costa Blanca S&uuml;d",
"keywords":"Costa Blanca Zu Vermietende Ferienunterk&auml;nfte",
"title":"Costa Blanca Immobilien Zu Vermietende Ferienunterk&auml;nfte",
"h1":"Immobilien Zu Vermietende Ferienunterk&auml;Nfte Costa Blanca S&uuml;d",
"pagename_en":"costa-blanca-holiday-rental-property-",
"pagename_nl":"Vakantieverhuur-costa-blanca-zuid-",
"pagename_fr":"Maisons-de-vacances-a-louer-Costa-Blanca-Sud-",
"pagename_de":"costa-blanca-FerienunterkuNfte-"
},
{
"rubrun":"Key Ready",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND blnoffplan = 1 ORDER BY intprice ASC",
"description":"neue H&auml;user zum Verkauf in Costa Blanca S&uuml;d.",
"keywords":"neue Ferienwohnungen, neue Stadth&auml;user, neue villas, Costa Blanca S&uuml;d",
"title":"neue H&auml;user zum Verkauf in Costa Blanca S&uuml;d",
"h1":"neue H&auml;user Villamartin, Cabo Roig, Campoamor, Playa Flamenca Costa Blanca S&uuml;d",
"pagename_en":"key-ready-homes-costa-blanca-south-",
"pagename_nl":"nieuwbouw-costa-blanca-zuid-",
"pagename_fr":"nouvelles-constructions-Costa-Blanca-Sud-",
"pagename_de":"neue-Hauser-costa-blanca-sud-"
},
{
"rubrun":"penthouse",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnpenthouse = 1 ORDER BY intprice ASC",
"description":"Penthouse Ferienwohnungen und penthouse duplex in Costa Blanca S&uuml;d",
"keywords":"penthouse Ferienwohnungen,Costa Blanca S&uuml;d, Spanien",
"title":"Penthouse Ferienwohnungen Costa Blanca S&uuml;d",
"h1":"Penthouse Ferienwohnungen zu verkaufen Costa Blanca S&uuml;d",
"pagename_en":"penthouse-apartments-south-costa-blanca-",
"pagename_nl":"Penthouse-dakappartement-costa-blanca-zuid-",
"pagename_fr":"Appartements-a-deux-etages-Costa-Blanca-Sud-",
"pagename_de":"penthouse-Ferienwohnungen-costa-blanca-sud-"
},
{
"rubrun":"beach",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnbeach = 1 ORDER BY intprice ASC",
"description":"Immobilien zu verkaufen at the beach in Costa Blanca S&uuml;d",
"keywords":"Strand Ferienwohnungen,Strand Stadth&auml;user, Strand villas, Costa Blanca S&uuml;d, Spanien",
"title":"Strand Immobilien Costa Blanca S&uuml;d",
"h1":"Ferienwohnungen, Stadth&auml;user, Villas N&auml;he zum Strand - Costa Blanca S&uuml;d, Spanien",
"pagename_en":"beach-property-south-costa-blanca-",
"pagename_nl":"Eigendom-aan-het-strand-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-sur-la-plage-Costa-Blanca-Sud-",
"pagename_de":"Strand-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"golf",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blngolf = 1 ORDER BY intprice ASC",
"description":"Golf Immobilien zu verkaufen in Costa Blanca S&uuml;d",
"keywords":"golf Ferienwohnungen,golf Stadth&auml;user, golf villas, Costa Blanca S&uuml;d, Spanien",
"title":"Immobilien in der N&auml;he des Golfplatzes auf dem Golfplatz Costa Blanca S&uuml;d",
"h1":"Golf Ferienwohnungen, Golf Stadth&auml;user, Golf Villas - Costa Blanca S&uuml;d, Spanien",
"pagename_en":"golf-property-south-costa-blanca-",
"pagename_nl":"Eigendom-aan-de-golf-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-sur-le-golf-resort-Costa-Blanca-Sud-",
"pagename_de":"golf-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Apartment",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND strpropertytype = 'Apartment' ORDER BY intprice ASC",
"description":"Ferienwohnungen zu verkaufen Costa Blanca S&uuml;d",
"keywords":"spanische Wohnung, wohnung costa blanca, wohnung Spanien, Strand-wohnung, golf-Wohnung, Luxus-Wohnung, Penthouse-Wohnung",
"title":"Ferienwohnungen zu verkaufen Costa Blanca S&uuml;d",
"h1":"Wohnungen Villamartin, Cabo Roig, Campoamor, Playa Flamenca Costa Blanca S&uuml;d",
"pagename_en":"apartments-for-sale-costa-blanca-south-",
"pagename_nl":"Appartement-te-koop-costa-blanca-zuid-",
"pagename_fr":"Appartements-a-vendre-Costa-Blanca-Sud-",
"pagename_de":"Ferienwohnungen-zu-verkaufen-costa-blanca-sud-"
},
{
"rubrun":"Townhouse",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND strpropertytype = 'Townhouse' ORDER BY intprice ASC",
"description":"Reihenh&auml;user zu verkaufen Costa Blanca S&uuml;d",
"keywords":"spanische Reihenh&auml;user, costa blanca Reihenh&auml;user, Reihenh&auml;user Spanien, Strand Stadthaus, golf Reihenh&auml;user, luxury Reihenh&auml;user",
"title":"Reihenh&auml;user zu verkaufen Costa Blanca S&uuml;d",
"h1":"Reihenh&auml;user Villamartin, Cabo Roig, Campoamor, Playa Flamenca Costa Blanca S&uuml;d",
"pagename_en":"townhouses-for-sale-costa-blanca-south-",
"pagename_nl":"Geschakelde-woningen-Costa-Blanca-Zuid-",
"pagename_fr":"Maisons-mitoyennes-Costa-Blanca-Sud-",
"pagename_de":"Stadthauser-zu-verkaufen-costa-blanca-sud-"
},
{
"rubrun":"quadhouses",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND strpropertytype = 'Quadhouse' ORDER BY intprice ASC",
"description":"quadHaus zu verkaufen Costa Blanca S&uuml;d",
"keywords":"spanische quadHaus, costa blanca quadHaus, quadHaus Spanien, Strand quadHaus, golf quadHaus, gro&szlig;z&uuml;gig quadHaus",
"title":"Quadhaus zu verkaufen Costa Blanca S&uuml;d",
"h1":"Quadhaus Villamartin, Cabo Roig, Campoamor, Playa Flamenca Costa Blanca Sud",
"pagename_en":"quadhouses-for-sale-costa-blanca-south-",
"pagename_nl":"Kwadranthuizen-Costa-Blanca-Zuid-",
"pagename_fr":"Maisons-mitoyennes-quatre-Costa-Blanca-Sud-",
"pagename_de":"quadhaus-zu-verkaufen-costa-blanca-sud-"
},
{
"rubrun":"Semidetached Villa",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND strpropertytype = 'Semidetached Villa' ORDER BY intprice ASC",
"description":"Doppelhaus Villa zu verkaufen Costa Blanca S&uuml;d",
"keywords":"spanische Doppelhaus Villa, costa blanca Doppelhaus Villa, Doppelhaus Villa Spanien, Strand Doppelhaus Villa, golf Doppelhaus Villa, gro&szlig;z&uuml;gig Doppelhaus Villa",
"title":"Doppelhaus Villa zu verkaufen Costa Blanca S&uuml;d",
"h1":"Doppelhaus Villa Villamartin, Cabo Roig, Campoamor, Playa Flamenca Costa Blanca S&uuml;d",
"pagename_en":"semidetached-villas-for-sale-costa-blanca-south-",
"pagename_nl":"Half-vrijstaande-villas-Costa-Blanca-Zuid-",
"pagename_fr":"Villas-jumelees-Costa-Blanca-Sud-",
"pagename_de":"Doppelhaus-villa-zu-verkaufen-costa-blanca-sud-"
},
{
"rubrun":"Villa",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND (strpropertytype = 'Villa' OR strpropertytype = 'Detached Villa') ORDER BY intprice ASC",
"description":"Villas zu verkaufen Costa Blanca S&uuml;d",
"keywords":"spanische villa, costa blanca villa, villas Spanien, Strand villa, golf villa, gro&szlig;z&uuml;gig villa",
"title":"Villas zu verkaufen Costa Blanca S&uuml;d",
"h1":"Villas Villamartin, Cabo Roig, Campoamor, Playa Flamenca Costa Blanca S&uuml;d",
"pagename_en":"villas-for-sale-costa-blanca-south-",
"pagename_nl":"Villas-Costa-Blanca-Zuid-",
"pagename_fr":"Villas-Costa-Blanca-Sud-",
"pagename_de":"villas-zu-verkaufen-costa-blanca-south-"
},
{
"rubrun":"fincas",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnfinca = 1 ORDER BY intprice ASC",
"description":"L&auml;ndliche Landh&auml;user zu verkaufen Costa Blanca S&uuml;d",
"keywords":"spanische L&auml;ndliche Landh&auml;user, costa blanca L&auml;ndliche Landh&auml;user, L&auml;ndliche Landh&auml;user Spanien, gro&szlig;z&uuml;gig L&auml;ndliche Landh&auml;user",
"title":"L&auml;ndliche Landh&auml;user zu verkaufen Costa Blanca S&uuml;d",
"h1":"L&auml;ndliche Landh&auml;user Costa Blanca S&uuml;d",
"pagename_en":"fincas-and-country-homes-for-sale-costa-blanca-south-",
"pagename_nl":"Fincas-en-landhuizen-Costa-Blanca-Zuid-",
"pagename_fr":"Fincas-et-maisons-de-campagne-Costa-Blanca-Sud-",
"pagename_de":"Landliche-Landhauser-zu-verkaufen-costa-blanca-south-"
},
{
"rubrun":"Luxury",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND blnluxury = 1 ORDER BY intprice ASC",
"description":"Luxus Immobilien zu verkaufen in Costa Blanca S&uuml;d",
"keywords":"luxury Ferienwohnungen,luxury Stadth&auml;user, luxury villas, Costa Blanca S&uuml;d, Spanien",
"title":"Luxus Immobilien zu verkaufen Costa Blanca S&uuml;d",
"h1":"Luxus Immobilien zu verkaufen Villamartin, Cabo Roig, Campoamor, Playa Flamenca Costa Blanca S&uuml;d",
"pagename_en":"luxury-property-south-costa-blanca-",
"pagename_nl":"Luxe-eigendom-te-koop-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-de-luxe-a-vendre-Costa-Blanca-Sud-",
"pagename_de":"Luxus-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Orihuela Costa",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strtown = 'Orihuela Costa' ORDER BY intprice ASC",
"description":"Orihuela Costa Immobilien zu verkaufen in Costa Blanca S&uuml;d",
"keywords":"Orihuela Costa Ferienwohnungen,Orihuela Costa Stadth&auml;user, Orihuela Costa villas, Costa Blanca S&uuml;d, Spanien",
"title":"Orihuela Costa Immobilien zu verkaufen Costa Blanca S&uuml;d",
"h1":"Immobilien zu verkaufen Orihuela Costa, Villamartin, Cabo Roig, Campoamor, Playa Flamenca",
"pagename_en":"orihuela-costa-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Orihuela-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Orihuela-Costa-Costa-Blanca-Sud-",
"pagename_de":"orihuela-costa-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Villamartin",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail IN('Villamartin','Villamartin Golf') ORDER BY intprice ASC",
"description":"Villamartin Immobilien zu verkaufen in Costa Blanca S&uuml;d",
"keywords":"Villamartin Ferienwohnungen, Villamartin Stadth&auml;user, Villamartin villas, Costa Blanca S&uuml;d, Spanien",
"title":"Villamartin Immobilien zu verkaufen Costa Blanca S&uuml;d",
"h1":"Villamartin Immobilien zu verkaufen",
"pagename_en":"villamartin-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Villamartin-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Villamartin-Costa-Blanca-Sud-",
"pagename_de":"villamartin-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Playa Flamenca",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail ='Playa Flamenca' ORDER BY intprice ASC",
"description":"Playa Flamenca Immobilien zu verkaufen in Costa Blanca S&uuml;d",
"keywords":"Playa Flamenca Ferienwohnungen, Playa Flamenca Stadth&auml;user, Playa Flamenca villas, Costa Blanca S&uuml;d, Spanien",
"title":"Playa Flamenca Immobilien zu verkaufen Costa Blanca S&uuml;d",
"h1":"Playa Flamenca Immobilien zu verkaufen",
"pagename_en":"playa-flamenca-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Playa-Flamenca-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Playa-Flamenca-Costa-Blanca-Sud-",
"pagename_de":"playa-flamenca-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Cabo Roig",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail ='Cabo Roig' ORDER BY intprice ASC",
"description":"Cabo Roig Immobilien zu verkaufen in Costa Blanca S&uuml;d",
"keywords":"Cabo Roig Ferienwohnungen, Cabo Roig Stadth&auml;user, Cabo Roig villas, Costa Blanca S&uuml;d, Spanien",
"title":"Cabo Roig Immobilien zu verkaufen Costa Blanca S&uuml;d",
"h1":"Cabo Roig Immobilien zu verkaufen",
"pagename_en":"cabo-roig-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Cabo-Roig-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Cabo-Roig-Costa-Blanca-Sud-",
"pagename_de":"cabo-roig-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Guardamar del Segura",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail IN('Guardamar','Guardamar del Segura','Guardamar Campo') ORDER BY intprice ASC",
"description":"Guardamar del Segura Immobilien zu verkaufen in Costa Blanca S&uuml;d",
"keywords":"Guardamar del Segura Ferienwohnungen, Guardamar del Segura Stadth&auml;user, Guardamar del Segura villas, Costa Blanca S&uuml;d, Spanien",
"title":"Guardamar del Segura Immobilien zu verkaufen Costa Blanca S&uuml;d",
"h1":"Guardamar del Segura Immobilien zu verkaufen",
"pagename_en":"guardamar-del-segura-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Guardamar-del-Segura-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Guardamar-del-Segura-Costa-Blanca-Sud-",
"pagename_de":"guardamar-del-segura-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Quesada",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail LIKE('%Quesada%') ORDER BY intprice ASC",
"description":"Quesada Immobilien zu verkaufen in Costa Blanca S&uuml;d",
"keywords":"Quesada Ferienwohnungen, Quesada Stadth&auml;user, Quesada villas, Costa Blanca S&uuml;d, Spanien",
"title":"Quesada Immobilien zu verkaufen Costa Blanca S&uuml;d",
"h1":"Quesada Immobilien zu verkaufen",
"pagename_en":"quesada-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Quesada-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Quesada-Costa-Blanca-Sud-",
"pagename_de":"quesada-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"La Zenia",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'La Zenia' ORDER BY intprice ASC",
"description":"La Zenia Immobilien zu verkaufen in Costa Blanca S&uuml;d",
"keywords":"La Zenia Ferienwohnungen, La Zenia Stadth&auml;user, La Zenia villas, Costa Blanca S&uuml;d, Spanien",
"title":"La Zenia Immobilien zu verkaufen Costa Blanca S&uuml;d",
"h1":"La Zenia Immobilien zu verkaufen",
"pagename_en":"la-zenia-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-La-Zenia-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-La-ZeniaCosta-Blanca-Sud-",
"pagename_de":"la-zenia-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Los Balcones",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'Los Balcones' ORDER BY intprice ASC",
"description":"Los Balcones Immobilien zu verkaufen in Costa Blanca S&uuml;d",
"keywords":"Los Balcones Ferienwohnungen, Los Balcones Stadth&auml;user, Los Balcones villas, Costa Blanca S&uuml;d, Spanien",
"title":"Los Balcones Immobilien zu verkaufen Costa Blanca S&uuml;d",
"h1":"Los Balcones Immobilien zu verkaufen",
"pagename_en":"los-balcones-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Los-Balcones-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Los-Balcones-Costa-Blanca-Sud-",
"pagename_de":"los-balcones-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Punta Prima",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'Punta Prima' ORDER BY intprice ASC",
"description":"Punta Prima Immobilien zu verkaufen in Costa Blanca S&uuml;d",
"keywords":"Punta Prima Ferienwohnungen, Costa Blanca S&uuml;d, Spanien",
"title":"Punta Prima Immobilien zu verkaufen Costa Blanca S&uuml;d",
"h1":"Punta Prima Immobilien zu verkaufen",
"pagename_en":"punta-prima-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Punta-Prima-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Punta-Prima-Costa-Blanca-Sud-",
"pagename_de":"punta-prima-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Alameda",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail LIKE ('%Alameda%') ORDER BY intprice ASC",
"description":"Alameda Immobilien zu verkaufen in Costa Blanca S&uuml;d",
"keywords":"Alameda Ferienwohnungen, Alameda Stadth&auml;user, Alameda villas, Costa Blanca S&uuml;d, Spanien",
"title":"Alameda Immobilien zu verkaufen Costa Blanca S&uuml;d",
"h1":"Alameda Immobilien zu verkaufen",
"pagename_en":"alameda-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Alameda-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Alameda-Costa-Blanca-Sud-",
"pagename_de":"alameda-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Campoamor",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail LIKE ('%Campoamor%') ORDER BY intprice ASC",
"description":"Campoamor Immobilien zu verkaufen in Costa Blanca S&uuml;d",
"keywords":"Campoamor Ferienwohnungen, Campoamor Stadth&auml;user, Campoamor villas, Costa Blanca S&uuml;d, Spanien",
"title":"Campoamor Immobilien zu verkaufen Costa Blanca S&uuml;d",
"h1":"Campoamor Immobilien zu verkaufen",
"pagename_en":"campoamor-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Campoamor-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Campoamor-Costa-Blanca-Sud-",
"pagename_de":"campoamor-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Las Filipinas",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'Las Filipinas' ORDER BY intprice ASC",
"description":"Las Filipinas Immobilien zu verkaufen in Costa Blanca S&uuml;d",
"keywords":"Las Filipinas Ferienwohnungen, Las Filipinas Stadth&auml;user, Las Filipinas villas, Costa Blanca S&uuml;d, Spanien",
"title":"Las Filipinas Immobilien zu verkaufen Costa Blanca S&uuml;d",
"h1":"Las Filipinas Immobilien zu verkaufen",
"pagename_en":"las-filipinas-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Las-Filipinas-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Las-Filipinas-Costa-Blanca-Sud-",
"pagename_de":"las-filipinas-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Los Dolses",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'Los Dolses' ORDER BY intprice ASC",
"description":"Los Dolses Immobilien zu verkaufen in Costa Blanca S&uuml;d",
"keywords":"Los Dolses Ferienwohnungen, Los Dolses Stadth&auml;user, Los Dolses villas, Costa Blanca S&uuml;d, Spanien",
"title":"Los Dolses Immobilien zu verkaufen Costa Blanca S&uuml;d",
"h1":"Los Dolses Immobilien zu verkaufen",
"pagename_en":"los-dolses-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Los-Dolses-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Los-Dolses-Costa-Blanca-Sud-",
"pagename_de":"los-dolses-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Las Ramblas",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'Las Ramblas' ORDER BY intprice ASC",
"description":"Las Ramblas Immobilien zu verkaufen in Costa Blanca S&uuml;d",
"keywords":"Las Ramblas Ferienwohnungen, Las Ramblas Stadth&auml;user, Las Ramblas villas, Costa Blanca S&uuml;d, Spanien",
"title":"Las Ramblas Immobilien zu verkaufen Costa Blanca S&uuml;d",
"h1":"Las Ramblas Immobilien zu verkaufen",
"pagename_en":"las-ramblas-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Las-Ramblas-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Las-Ramblas-Costa-Blanca-Sud-",
"pagename_de":"las-ramblas-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Rio Mar",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'Rio Mar' ORDER BY intprice ASC",
"description":"Rio Mar Immobilien zu verkaufen in Costa Blanca S&uuml;d",
"keywords":"Rio Mar Ferienwohnungen, Rio Mar Stadth&auml;user, Rio Mar villas, Costa Blanca S&uuml;d, Spanien",
"title":"Rio Mar Immobilien zu verkaufen Costa Blanca S&uuml;d",
"h1":"Rio Mar Immobilien zu verkaufen",
"pagename_en":"rio-mar-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Rio-Mar-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Rio-Mar-Costa-Blanca-Sud-",
"pagename_de":"rio-mar-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Torrevieja",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strtown = 'Torrevieja' ORDER BY intprice ASC",
"description":"Torrevieja Immobilien zu verkaufen in Costa Blanca S&uuml;d",
"keywords":"Torrevieja Ferienwohnungen, Torrevieja Stadth&auml;user, Torrevieja villas, Costa Blanca S&uuml;d, Spanien",
"title":"Torrevieja Immobilien zu verkaufen Costa Blanca S&uuml;d",
"h1":"Torrevieja Immobilien zu verkaufen",
"pagename_en":"torrevieja-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Torrevieja-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Torrevieja-Costa-Blanca-Sud-",
"pagename_de":"torrevieja-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Dream Hills",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'Dream Hills' ORDER BY intprice ASC",
"description":"Dream Hills Immobilien zu verkaufen in Costa Blanca S&uuml;d",
"keywords":"Dream Hills Ferienwohnungen, Dream Hills Stadth&auml;user, Dream Hills villas, Costa Blanca S&uuml;d, Spanien",
"title":"Dream Hills Immobilien zu verkaufen Costa Blanca S&uuml;d",
"h1":"Dream Hills Immobilien zu verkaufen",
"pagename_en":"dream-hills-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Dream-Hills-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Dream-Hills-Costa-Blanca-Sud-",
"pagename_de":"dream-hills-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Algorfa",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'Algorfa' ORDER BY intprice ASC",
"description":"Algorfa Immobilien zu verkaufen in Costa Blanca S&uuml;d",
"keywords":"Algorfa Ferienwohnungen, Algorfa Stadth&auml;user, Algorfa villas, Costa Blanca S&uuml;d, Spanien",
"title":"Algorfa Immobilien zu verkaufen Costa Blanca S&uuml;d",
"h1":"Algorfa Immobilien zu verkaufen",
"pagename_en":"algorfa-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Algorfa-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Algorfa-Costa-Blanca-Sud-",
"pagename_de":"algorfa-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"La Mata",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'La Mata' ORDER BY intprice ASC",
"description":"La Mata Immobilien zu verkaufen in Costa Blanca S&uuml;d",
"keywords":"La Mata Ferienwohnungen, La Mata Stadth&auml;user, La Mata villas, Costa Blanca S&uuml;d, Spanien",
"title":"La Mata Immobilien zu verkaufen Costa Blanca S&uuml;d",
"h1":"La Mata Immobilien zu verkaufen",
"pagename_en":"la-mata-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-La-Mata-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-La-Mata-Costa-Blanca-Sud-",
"pagename_de":"la-mata-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"La Torreta",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'La Torreta' ORDER BY intprice ASC",
"description":"La Torreta Immobilien zu verkaufen in Costa Blanca S&uuml;d",
"keywords":"La Torreta Ferienwohnungen, La Torreta Stadth&auml;user, La Torreta villas, Costa Blanca S&uuml;d, Spanien",
"title":"La Torreta Immobilien zu verkaufen Costa Blanca S&uuml;d",
"h1":"La Torreta Immobilien zu verkaufen",
"pagename_en":"la-torreta-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-La-Torreta-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-La-Torreta-Costa-Blanca-Sud-",
"pagename_de":"la-torreta-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Los Altos",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'Los Altos' ORDER BY intprice ASC",
"description":"Los Altos Immobilien zu verkaufen in Costa Blanca S&uuml;d",
"keywords":"Los Altos Ferienwohnungen, Los Altos Stadth&auml;user, Los Altos villas, Costa Blanca S&uuml;d, Spanien",
"title":"Los Altos Immobilien zu verkaufen Costa Blanca S&uuml;d",
"h1":"Los Altos Immobilien zu verkaufen",
"pagename_en":"los-altos-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Los-Altos-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Los-Altos-Costa-Blanca-Sud-",
"pagename_de":"los-altos-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Mar Azul",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'Mar Azul' ORDER BY intprice ASC",
"description":"Mar Azul Immobilien zu verkaufen in Costa Blanca S&uuml;d",
"keywords":"Mar Azul Ferienwohnungen, Mar Azul Stadth&auml;user, Mar Azul villas, Costa Blanca S&uuml;d, Spanien",
"title":"Mar Azul Immobilien zu verkaufen Costa Blanca S&uuml;d",
"h1":"Mar Azul Immobilien zu verkaufen",
"pagename_en":"mar-azul-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Mar-Azul-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Mar-Azul-Costa-Blanca-Sud-",
"pagename_de":"mar-azul-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Miraflores",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'Miraflores' ORDER BY intprice ASC",
"description":"Miraflores Immobilien zu verkaufen in Costa Blanca S&uuml;d",
"keywords":"Miraflores Ferienwohnungen, Miraflores Stadth&auml;user, Miraflores villas, Costa Blanca S&uuml;d, Spanien",
"title":"Miraflores Immobilien zu verkaufen Costa Blanca S&uuml;d",
"h1":"Miraflores Immobilien zu verkaufen",
"pagename_en":"miraflores-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Miraflores-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Miraflores-Costa-Blanca-Sud-",
"pagename_de":"miraflores-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Rocio del Mar",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'Rocio del Mar' ORDER BY intprice ASC",
"description":"Rocio del Mar Immobilien zu verkaufen in Costa Blanca S&uuml;d",
"keywords":"Rocio del Mar Ferienwohnungen, Rocio del Mar Stadth&auml;user, Rocio del Mar villas, Costa Blanca S&uuml;d, Spanien",
"title":"Rocio del Mar Immobilien zu verkaufen Costa Blanca S&uuml;d",
"h1":"Rocio del Mar Immobilien zu verkaufen",
"pagename_en":"rocio-del-mar-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Rocio-del-Mar-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Rocio-del-Mar-Costa-Blanca-Sud-",
"pagename_de":"rocio-del-mar-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"La Manga",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail Like 'La Manga%' ORDER BY intprice ASC",
"description":"La Manga Immobilien zu verkaufen in Costa Blanca S&uuml;d",
"keywords":"La Manga Ferienwohnungen, La Manga Stadth&auml;user, La Manga villas, Costa Blanca S&uuml;d, Spanien",
"title":"La Manga Immobilien zu verkaufen Murcia",
"h1":"La Manga del Mar Menor Immobilien zu verkaufen",
"pagename_en":"la-manga-property-murcia-",
"pagename_nl":"Eigendom-te-koop-in-La-Manga-del-Mar-Menor-",
"pagename_fr":"Propriete-a-vendre-a-La-Manga-del-Mar-Menor-",
"pagename_de":"la-manga-Immobilien-murcia-"
},
{
"rubrun":"Los Alcazares",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strtown = 'Los Alcazares' ORDER BY intprice ASC",
"description":"Los Alcazares Immobilien zu verkaufen in Costa Blanca S&uuml;d",
"keywords":"Los Alcazares Ferienwohnungen, Los Alcazares Stadth&auml;user, Los Alcazares villas, Costa Blanca S&uuml;d, Spanien",
"title":"Los Alcazares Immobilien zu verkaufen Murcia",
"h1":"Los Alcazares Immobilien zu verkaufen",
"pagename_en":"los-alcazares-property-murcia-",
"pagename_nl":"Eigendom-te-koop-in-Los-Alcazares-murcia-",
"pagename_fr":"Propriete-a-vendre-a-Los-Alcazares-Murcia-",
"pagename_de":"los-alcazares-Immobilien-murcia-"
}
]
