rubruns=[
{
"rubrun":"All-props",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND blnrental = 0 ORDER BY intprice ASC",
"description":"Villa's, appartementen, geschakelde woningen en finca's te koop in Villamartin, Playa Flamenca, Cabo Roig, Los Altos, Los Balcones, Guardamar del Segura, Ciudad Quesada, Torrevieja en Costa Blanca Zuid, Spanje",
"keywords":"Villa's, appartementen geschakelde woningen en finca's in Villamartin, Playa Flamenca, Cabo Roig, Guardamar del Segura en Ciudad Quesada",
"title":"Villa's, appartementen, geschakelde woningen en finca's te koop in Playa Flamenca, Cabo Roig, Guardamar del Segura, Ciudad Quesada, Costa Blanca Zuid",
"h1":"Eigendom te koop in Villamartin, Cabo Roig, Torrevieja, Playa Flamenca en Orihuela Costa, Spanje",
"pagename_en":"villas-apartments-townhouses-and-fincas-for-sale-",
"pagename_nl":"villas-appartementen-geschakelde-woningen-en-fincas-te-koop-",
"pagename_fr":"Villas-appartements-maisons-mitoyennes-et-fincas-a-vendre-",
"pagename_de":"villas-Ferienwohnungen-Stadthauser-und-fincas-zu-verkaufen-"
},
{
"rubrun":"Up to 100000",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND blnrental = 0 AND intprice <= 100000 ORDER BY intprice ASC",
"description":"Villa's, appartementen, geschakelde woningen en Spaanse huizen tot 100.000 euro",
"keywords":"Goedkope villa's, goedkope appartementen, goedkope appartementen en geschakelde woningen Costa Blanca",
"title":"Eigendom aan de Costa Blanca tot 100.000 euro",
"h1":"Eigendom te koop in Villamartin, Cabo Roig, Torrevieja, Playa Flamenca, Costa Blanca Zuid tot &euro;100.000",
"pagename_en":"costa-blanca-property-for-less-than-100000-",
"pagename_nl":"Eigendom-in-de-Costa-Blanca-tot-100000-euro-",
"pagename_fr":"Propriete-a-Costa-Blanca-jusqu-a-100000-euro-",
"pagename_de":"costa-blanca-Immobilien-fur-weniger-als-100000-"
},
{
"rubrun":"101000-200000",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND blnrental = 0 AND intprice >= 101000  AND intprice <= 200000 ORDER BY intprice ASC",
"description":"Villa's, appartementen, geschakelde woningen en Spaanse huizen van 100.000 euro tot 200.000 euro",
"keywords":"Voordelige villa's, voordelige appartementen, goedkope appartementen en geschakelde woningen Costa Blanca",
"title":"Eigendom aan de Costa Blanca van 100.000 euro tot 200.000 euro",
"h1":"Eigendom te koop in Villamartin, Cabo Roig, Torrevieja, Playa Flamenca, Costa Blanca Zuid van &euro;100.000 tot &euro;200.000",
"pagename_en":"costa-blanca-property-from-100000-to-200000-",
"pagename_nl":"Eigendom-aan-de-Costa-Blanca-van-100000-tot-200000-euro-",
"pagename_fr":"Propriete-a-Costa-Blanca-de-100000-euro-a-200000-euro-",
"pagename_de":"costa-blanca-Immobilien-von-100000-bis-200000-"
},
{
"rubrun":"201000-300000",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND blnrental = 0 AND intprice >= 201000  AND intprice <= 300000 ORDER BY intprice ASC",
"description":"Villa's, appartementen, geschakelde woningen en Spaanse huizen van 200.000 euro tot 300.000 euro",
"keywords":"Populaire villa's, aangename appartementen, prachtige huizen Costa Blanca",
"title":"Eigendom aan de Costa Blanca van 200.000 euro tot 300.000 euro",
"h1":"Eigendom te koop in Villamartin, Cabo Roig, Torrevieja, Playa Flamenca, Costa Blanca Zuid van &euro;200.000 tot &euro;300.000",
"pagename_en":"costa-blanca-property-from-200000-to-300000-",
"pagename_nl":"Eigendom-aan-de-Costa-Blanca-van-200000-tot-300000-euro-",
"pagename_fr":"Propriete-a-Costa-Blanca-de-200000-euro-a-300000-euro-",
"pagename_de":"costa-blanca-Immobilien-von-200000-bis-300000-"
},
{
"rubrun":"301000-400000",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND blnrental = 0 AND intprice >= 301000  AND intprice <= 400000 ORDER BY intprice ASC",
"description":"Villa's, appartementen, geschakelde woningen en Spaanse huizen van 300.000 euro tot 400.000 euro",
"keywords":"Prachtige villa's, luxe-appartementen en huizen voor gepensioneerden Costa Blanca",
"title":"Eigendom aan de Costa Blanca van 300.000 euro tot 400.000 euro",
"h1":"Eigendom te koop in Villamartin, Cabo Roig, Torrevieja, Playa Flamenca, en Costa Blanca Zuid van &euro;300.000 tot &euro;400.000",
"pagename_en":"costa-blanca-property-from-300000-to-400000-",
"pagename_nl":"Eigendom-aan-de-Costa-Blanca-van-300000-tot-400000-euro-",
"pagename_fr":"Propriete-a-Costa-Blanca-de-300000-euro-a-400000-euro-",
"pagename_de":"costa-blanca-Immobilien-von-300000-bis-400000-"
},
{
"rubrun":"401000-500000",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND blnrental = 0 AND intprice >= 401000  AND intprice <= 500000 ORDER BY intprice ASC",
"description":"Appartementen, geschakelde woningen en Spaanse villa's van 400.000 euro tot 500.000 euro",
"keywords":"Goed uitgeruste appartementen en villa's, comfortabele huizen Costa Blanca",
"title":"Eigendom aan de Costa Blanca van 400.000 euro tot 500.000 euro",
"h1":"Eigendom te koop in Villamartin, Cabo Roig, Torrevieja, Playa Flamenca, Costa Blanca Zuid van &euro;400.000 tot &euro;500.000",
"pagename_en":"costa-blanca-property-from-400000-to-500000-",
"pagename_nl":"Eigendom-aan-de-Costa-Blanca-van-400000-tot-500000-euro-",
"pagename_fr":"Propriete-a-Costa-Blanca-de-400000-euro-a-500000-euro-",
"pagename_de":"costa-blanca-Immobilien-von-400000-bis-500000-"
},
{
"rubrun":"501000-600000",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND blnrental = 0 AND intprice >= 501000  AND intprice <= 600000 ORDER BY intprice ASC",
"description":"Appartementen, geschakelde woningen en Spaanse villa's van 500.000 euro tot 600.000 euro",
"keywords":"Huizen Costa Blanca, villa's, appartementen, huizen aan de golf, eigendommen Costa Blanca Zuid, Spanje",
"title":"Eigendom aan de Costa Blanca van 500.000 euro tot 600.000 euro",
"h1":"Eigendom te koop in Villamartin, Cabo Roig, Campoamor, Playa Flamenca, Costa Blanca Zuid van &euro;500.000 tot &euro;600.000",
"pagename_en":"costa-blanca-property-from-500000-to-600000-",
"pagename_nl":"Eigendom-aan-de-Costa-Blanca-van-500000-tot-600000-euro-",
"pagename_fr":"Propriete-a-Costa-Blanca-de-500000-euro-a-600000-euro-",
"pagename_de":"costa-blanca-Immobilien-von-500000-bis-600000-"
},
{
"rubrun":"601000-700000",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND blnrental = 0 AND intprice >= 601000  AND intprice <= 700000 ORDER BY intprice ASC",
"description":"Appartementen, geschakelde woningen en Spaanse villa's van 600.000 euro tot 700.000 euro",
"keywords":"Costa Blanca homes, Villas, Apartments, Golf homes, Property South Costa Blanca, Spain",
"title":"Eigendom aan de Costa Blanca van 600.000 euro tot 700.000 euro",
"h1":"Eigendom te koop in Villamartin, Cabo Roig, Campoamor, Playa Flamenca, Costa Blanca Zuid van &euro;600.000 tot &euro;700.000",
"pagename_en":"costa-blanca-property-from-600000-to-700000-",
"pagename_nl":"Eigendom-aan-de-Costa-Blanca-van-600000-tot-700000-euro-",
"pagename_fr":"Propriete-a-Costa-Blanca-de-600000-euro-a-700000-euro-",
"pagename_de":"costa-blanca-Immobilien-von-600000-bis-700000-"
},
{
"rubrun":"701000-800000",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND blnrental = 0 AND intprice >= 701000  AND intprice <= 800000 ORDER BY intprice ASC",
"description":"Appartementen, geschakelde woningen en Spaanse villa's van &euro;700.000 tot &euro;800.000",
"keywords":"Comfortabele huizen Costa Blanca, villa's, appartementen, huizen aan de golf, eigendommen Costa Blanca Zuid, Spanje",
"title":"Eigendom aan de Costa Blanca van 700.000 euro tot 800.000 euro",
"h1":"Eigendom te koop in Villamartin, Cabo Roig, Campoamor, Playa Flamenca, Costa Blanca Zuid van &euro;700.000 tot &euro;800.000",
"pagename_en":"costa-blanca-property-from-700000-to-800000-",
"pagename_nl":"Eigendom-aan-de-Costa-Blanca-van-700000-tot-800000-euro-",
"pagename_fr":"Propriete-a-Costa-Blanca-de-700000-euro-a-800000-euro-",
"pagename_de":"costa-blanca-Immobilien-von-700000-bis-800000-"
},
{
"rubrun":"801000-900000",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND blnrental = 0 AND intprice >= 801000  AND intprice <= 900000 ORDER BY intprice ASC",
"description":"Appartementen, geschakelde woningen en Spaanse villa's van 800,000 euro tot 900,000 euro",
"keywords":"Luxueuze huizen Costa Blanca, villa's, appartementen, huizen aan de golf, eigendommen Costa Blanca Zuid, Spanje",
"title":"Eigendom aan de Costa Blanca van 800.000 euro tot 900.000 euro",
"h1":"Eigendom te koop in Villamartin, Cabo Roig, Campoamor, Playa Flamenca, Costa Blanca Zuid van &euro;800.000 tot &euro;900.000",
"pagename_en":"costa-blanca-property-from-800000-to-900000-",
"pagename_nl":"Eigendom-aan-de-Costa-Blanca-van-800000-tot-900000-euro-",
"pagename_fr":"Propriete-a-Costa-Blanca-de-800000-euro-a-900000-euro-",
"pagename_de":"costa-blanca-Immobilien-von-800000-bis-900000-"
},
{
"rubrun":"more than 900000",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND blnrental = 0 AND intprice > 900000 ORDER BY intprice ASC",
"description":"Appartementen, geschakelde woningen en Spaanse villa's vanaf 900.000 euro",
"keywords":"Unieke huizen Costa Blanca, villa's, appartementen, huizen aan de golf, eigendommen Costa Blanca Zuid, Spanje",
"title":"Unieke eigendommen aan de Costa Blanca vanaf 900.000 euro",
"h1":"Eigendom te koop in Villamartin, Cabo Roig, Campoamor, Playa Flamenca, en de Costa Blanca Zuid vanaf &euro;900.000",
"pagename_en":"costa-blanca-property-from-900000-",
"pagename_nl":"Eigendom-aan-de-Costa-Blanca-vanaf-900000-euro-",
"pagename_fr":"Propriete-a-Costa-Blanca-a-partir-de-900000-euro-",
"pagename_de":"costa-blanca-Immobilien-von-900000-"
},
{
"rubrun":"apartments",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND strpropertytype = 'Apartment' ORDER BY intprice ASC",
"description":"Appartementen te koop aan de Costa Blanca Zuid",
"keywords":"Spaans appartement, appartement Costa Blanca Zuid, appartement Spanje, appartement strand, appartement golf, luxueuze appartement",
"title":"Appartementen te koop Costa Blanca Zuid",
"h1":"Appartementen in Villamartin, Cabo Roig, Campoamor, Playa Flamenca, Costa Blanca Zuid",
"pagename_en":"apartments-for-sale-costa-blanca-south-",
"pagename_nl":"Appartement-te-koop-costa-blanca-zuid-",
"pagename_fr":"Appartements-a-vendre-Costa-Blanca-Sud-",
"pagename_de":"Ferienwohnungen-zu-verkaufen-costa-blanca-sud-"
},
{
"rubrun":"Commercial",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND (strpropertytype IN ('Bar','Restaurant','Business','Commercial','Hotel')) ORDER BY intprice ASC",
"description":"Commerciele panden en kantoren in Costa Blanca Zuid, cafes, restaurants, hotels",
"keywords":"commerciele panden Costa Blanca, kantoren Costa Blanca, cafes, restaurants, hotels",
"title":"Commerci&euml;le panden aan de Costa Blanca",
"h1":"Commerci&euml;le panden Costa Blanca Zuid",
"pagename_en":"costa-blanca-commercial-property-",
"pagename_nl":"Commerciele-panden-Costa-Blanca-Zuid-",
"pagename_fr":"Batiments-commerciaux-Costa-Blanca-Sud-",
"pagename_de":"costa-blanca-Gewerbeimmobilien-"
},
{
"rubrun":"Long Term Rentals",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND blnrental = 1 AND strFrequency = 'month' ORDER BY intprice ASC",
"description":"Eigendom te huur voor lange termijn in Costa Blanca Zuid",
"keywords":"verhuur Costa Blanca, verhuur voor lange termijn, verhuur lange termijn",
"title":"Huizen aan de Costa Blanca voor lange-termijnverhuur",
"h1":"Eigendom te huur voor lange termijn Costa Blanca Zuid",
"pagename_en":"costa-blanca-long-term-rental-property-",
"pagename_nl":"Eigendom-te-huur-voor-lange-termijn-costa-blanca-zuid-",
"pagename_fr":"Propriete-a-louer-pour-long-terme-Costa-Blanca-Sud-",
"pagename_de":"costa-blanca-Langfristige-Vermietungen-"
},
{
"rubrun":"Holiday Rentals",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND blnrental = 1 AND strFrequency = 'week' ORDER BY intprice ASC",
"description":"Vakantieverhuur Costa Blanca Zuid",
"keywords":"Verhuur Costa Blanca, vakantieverhuur, vakantieverhuur",
"title":"Vakantieverhuur aan de Costa Blanca",
"h1":"Vakantieverhuur Costa Blanca Zuid",
"pagename_en":"costa-blanca-holiday-rental-property-",
"pagename_nl":"Vakantieverhuur-costa-blanca-zuid-",
"pagename_fr":"Maisons-de-vacances-a-louer-Costa-Blanca-Sud-",
"pagename_de":"costa-blanca-FerienunterkuNfte-"
},
{
"rubrun":"Key Ready",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND blnoffplan = 1 ORDER BY intprice ASC",
"description":"Eigendom in Costa Blanca Zuid. Sleutel op de deur en nieuwbouw aan het strand en in het binnenland",
"keywords":"Sleutel op de deur-appartementen, sleutel op de deur geschakelde woningen, sleutel op de deur villa's, Costa Blanca Zuid",
"title":"Sleutel op de deur-huizen Costa Blanca Zuid",
"h1":"Sleutel op de deur-eigendommen in Villamartin, Cabo Roig, Campoamor, Playa Flamenca, Costa Blanca Zuid",
"pagename_en":"key-ready-homes-costa-blanca-south-",
"pagename_nl":"nieuwbouw-costa-blanca-zuid-",
"pagename_fr":"nouvelles-constructions-Costa-Blanca-Sud-",
"pagename_de":"neue-Hauser-costa-blanca-sud-"
},
{
"rubrun":"penthouse",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnpenthouse = 1 ORDER BY intprice ASC",
"description":"Penthouse appartementen en penthouse duplexen in Costa Blanca Zuid",
"keywords":"penthouse appartementen, Costa Blanca Zuid, Spanje",
"title":"Penthouse appartementen in Costa Blanca Zuid",
"h1":"Penthouse appartementen te koop in Costa Blanca Zuid",
"pagename_en":"penthouse-apartments-south-costa-blanca-",
"pagename_nl":"Penthouse-dakappartement-costa-blanca-zuid-",
"pagename_fr":"Appartements-a-deux-etages-Costa-Blanca-Sud-",
"pagename_de":"penthouse-Ferienwohnungen-costa-blanca-sud-"
},
{
"rubrun":"beach",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnbeach = 1 ORDER BY intprice ASC",
"description":"Eigendom te koop aan het strand in Costa Blanca Zuid",
"keywords":"appartementen strand, geschakelde woningen strand, villa's strand, Costa Blanca Zuid, Spanje",
"title":"Eigendom aan het strand, Costa Blanca Zuid",
"h1":"Eigendom te koop aan het strand, Costa Blanca Zuid, Spanje",
"pagename_en":"beach-property-south-costa-blanca-",
"pagename_nl":"Eigendom-aan-het-strand-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-sur-la-plage-Costa-Blanca-Sud-",
"pagename_de":"Strand-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"golf",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blngolf = 1 ORDER BY intprice ASC",
"description":"Eigendom te koop aan de golf in Costa Blanca Zuid",
"keywords":"appartementen golf, geschakelde woningen golf, villa's golf, Costa Blanca Zuid, Spanje",
"title":"Eigendom te koop aan de golf in Costa Blanca Zuid",
"h1":"Eigendom te koop aan de golf - Costa Blanca Zuid, Spanje",
"pagename_en":"golf-property-south-costa-blanca-",
"pagename_nl":"Eigendom-aan-de-golf-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-sur-le-golf-resort-Costa-Blanca-Sud-",
"pagename_de":"golf-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"townhouses",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND strpropertytype = 'Townhouse' ORDER BY intprice ASC",
"description":"Geschakelde woningen te koop Costa Blanca Zuid",
"keywords":"geschakelde woning Spanje,  geschakelde woning Costa Blanca, geschakelde woningen Spanje, geschakelde woning strand, geschakelde woning golf, luxueuze geschakelde woning",
"title":"Geschakelde woningen te koop Costa Blanca Zuid",
"h1":"Geschakelde woningen in Villamartin, Cabo Roig, Campoamor, Playa Flamenca, Costa Blanca Zuid",
"pagename_en":"townhouses-for-sale-costa-blanca-south-",
"pagename_nl":"Geschakelde-woningen-Costa-Blanca-Zuid-",
"pagename_fr":"Maisons-mitoyennes-Costa-Blanca-Sud-",
"pagename_de":"Stadthauser-zu-verkaufen-costa-blanca-sud-"
},
{
"rubrun":"quadhouses",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND strpropertytype = 'Quadhouse' ORDER BY intprice ASC",
"description":"Kwadranthuizen (4 onder een dak) te koop Costa Blanca Zuid",
"keywords":"Kwadranthuis (4 onder een dak) Spanje, kwadranthuis (4 onder een dak) Costa Blanca, kwadranthuizen (4 onder een dak) Spanje,kwadranthuis (4 onder een dak) strand, kwadranthuis (4 onder een dak) golf, ruim kwadranthuis (4 onder een dak)",
"title":"Kwadranthuizen (4 onder een dak) te koop Costa Blanca Zuid.",
"h1":"Kwadranthuizen (4 onder een dak) in Villamartin, Cabo Roig, Campoamor, Playa Flamenca, Costa Blanca Zuid",
"pagename_en":"quadhouses-for-sale-costa-blanca-south-",
"pagename_nl":"Kwadranthuizen-Costa-Blanca-Zuid-",
"pagename_fr":"Maisons-mitoyennes-quatre-Costa-Blanca-Sud-",
"pagename_de":"quadhaus-zu-verkaufen-costa-blanca-sud-"
},
{
"rubrun":"Semidetached Villa",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND strpropertytype = 'Semidetached Villa' ORDER BY intprice ASC",
"description":"Half-vrijstaande villa's te koop Costa Blanca Zuid",
"keywords":"Half-vrijstaande villa's Spanje, half-vrijstaande villa's Costa Blanca. Half-vrijstaande villa's Spanje, half-vrijstaande villa aan het strand, half-vrijstaande villa aan de golf, ruimehalf-vrijstaande villa",
"title":"Half-vrijstaande villa's te koop Costa Blanca Zuid",
"h1":"Half-vrijstaande villa's In Villamartin, Cabo Roig, Campoamor, Playa Flamenca, Costa Blanca Zuid",
"pagename_en":"semidetached-villas-for-sale-costa-blanca-south-",
"pagename_nl":"Half-vrijstaande-villas-Costa-Blanca-Zuid-",
"pagename_fr":"Villas-jumelees-Costa-Blanca-Sud-",
"pagename_de":"Doppelhaus-villa-zu-verkaufen-costa-blanca-sud-"
},
{
"rubrun":"Villa",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND (strpropertytype = 'Villa' OR strpropertytype = 'Detached Villa') ORDER BY intprice ASC",
"description":"Villa's te koop Costa Blanca Zuid",
"keywords":"Spaanse villa, villa Costa Blanca, villa Spanje, villa aan de zee, villa aan de golf, ruime villa",
"title":"Villa's te koop Costa Blanca Zuid",
"h1":"Villa's Villamartin, Cabo roig, Campoamor, Playa Flamenca, Costa Blanca Zuid",
"pagename_en":"villas-for-sale-costa-blanca-south-",
"pagename_nl":"Villas-Costa-Blanca-Zuid-",
"pagename_fr":"Villas-Costa-Blanca-Sud-",
"pagename_de":"villas-zu-verkaufen-costa-blanca-south-"
},
{
"rubrun":"fincas",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnfinca = 1 ORDER BY intprice ASC",
"description":"Finca's en landhuizen te koop Costa Blanca Zuid",
"keywords":"Spaanse finca's en landhuizen, finca's en landhuizen Costa Blanca, finca's en landhuizen Spanje, ruime finca's en landhuizen",
"title":"Finca's en landhuizen te koop Costa Blanca Zuid",
"h1":"Finca's en landhuizen Costa Blanca Zuid",
"pagename_en":"fincas-and-country-homes-for-sale-costa-blanca-south-",
"pagename_nl":"Fincas-en-landhuizen-Costa-Blanca-Zuid-",
"pagename_fr":"Fincas-et-maisons-de-campagne-Costa-Blanca-Sud-",
"pagename_de":"Landliche-Landhauser-zu-verkaufen-costa-blanca-south-"
},
{
"rubrun":"Luxury",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND blnluxury = 1 ORDER BY intprice ASC",
"description":"Luxe-eigendom te koop in Costa Blanca Zuid",
"keywords":"luxe-appartementen, luxueuze geschakelde woningen, luxueuze villa's, Costa Blanca Zuid, Spanje",
"title":"Luxe-eigendom te koop Costa Blanca Zuid",
"h1":"Luxe-eigendom te koop in Villamartin, Cabo roig, Campoamor, Playa Flamenca, Costa Blanca Zuid",
"pagename_en":"luxury-property-south-costa-blanca-",
"pagename_nl":"Luxe-eigendom-te-koop-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-de-luxe-a-vendre-Costa-Blanca-Sud-",
"pagename_de":"Luxus-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Orihuela Costa",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strtown = 'Orihuela Costa' ORDER BY intprice ASC",
"description":"Eigendom te koop in Orihuela Costa, Costa Blanca Zuid",
"keywords":"Appartementen Orihuela Costa, geschakelde woningen Orihuela Costa, villa's Orihuela Costa, Costa Blanca Zuid, Spanje",
"title":"Eigendom te koop Orihuela Costa, Costa Blanca Zuid",
"h1":"Eigendom te koop Orihuela Costa, Villamartin, Cabo Roig, Campoamor, Playa Flamenca",
"pagename_en":"orihuela-costa-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Orihuela-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Orihuela-Costa-Costa-Blanca-Sud-",
"pagename_de":"orihuela-costa-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Villamartin",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail IN('Villamartin','Villamartin Golf') ORDER BY intprice ASC",
"description":"Villamartin property for sale in Costa Blanca South",
"keywords":"Appartementen Villamartin, geschakelde woningen Villamartin, villa's Villamartin, Costa Blanca Zuid, Spanje",
"title":"Eigendom te koop Villamartin, Costa Blanca Zuid",
"h1":"Eigendom te koop Villamartin",
"pagename_en":"villamartin-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Villamartin-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Villamartin-Costa-Blanca-Sud-",
"pagename_de":"villamartin-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Playa Flamenca",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail ='Playa Flamenca' ORDER BY intprice ASC",
"description":"Eigendom te koop in Playa Flamenca, Costa Blanca Zuid",
"keywords":"Appartementen Playa Flamenca, geschakelde woningen Playa Flamenca, villa's Playa Flamenca, Costa Blanca Zuid, Spanje",
"title":"Eigendom te koop Playa Flamenca, Costa Blanca Zuid",
"h1":"Eigendom te koop Playa Flamenca",
"pagename_en":"playa-flamenca-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Playa-Flamenca-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Playa-Flamenca-Costa-Blanca-Sud-",
"pagename_de":"playa-flamenca-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Cabo Roig",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail ='Cabo Roig' ORDER BY intprice ASC",
"description":"Eigendom te koop in Cabo Roig, Costa Blanca Zuid",
"keywords":"Appartementen Cabo Roig, geschakelde woningen Cabo Roig, villa's Cabo Roig, Costa Blanca Zuid, Spanje",
"title":"Eigendom te koop Cabo Roig, Costa Blanca Zuid",
"h1":"Eigendom te koop in Cabo Roig",
"pagename_en":"cabo-roig-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Cabo-Roig-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Cabo-Roig-Costa-Blanca-Sud-",
"pagename_de":"cabo-roig-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Guardamar del Segura",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail IN('Guardamar','Guardamar del Segura','Guardamar Campo') ORDER BY intprice ASC",
"description":"Eigendom te koop in Guardamar del Segura, Costa Blanca Zuid.",
"keywords":"Appartementen Guardamar del Segura, geschakelde woningen Guardamar del Segura, villa's Guardamar del Segura, Costa Blanca Zuid, Spanje",
"title":"Eigendom te koop Guardamar del Segura, Costa Blanca Zuid.",
"h1":"Eigendom te koop Guardamar del Segura",
"pagename_en":"guardamar-del-segura-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Guardamar-del-Segura-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Guardamar-del-Segura-Costa-Blanca-Sud-",
"pagename_de":"guardamar-del-segura-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Quesada",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail LIKE('%Quesada%') ORDER BY intprice ASC",
"description":"Eigendom te koop in Quesada, Costa Blanca Zuid",
"keywords":"Appartementen Quesada, geschakelde woningen Quesada, villa's Quesada, Costa Blanca Zuid, Spanj",
"title":"Eigendom te koop in Quesada, Costa Blanca Zuid",
"h1":"Eigendom te koop in Quesada",
"pagename_en":"quesada-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Quesada-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Quesada-Costa-Blanca-Sud-",
"pagename_de":"quesada-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"La Zenia",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'La Zenia' ORDER BY intprice ASC",
"description":"Eigendom te koop in La Zenia, Costa Blanca Zuid",
"keywords":"Appartementen La Zenia, geschakelde woningen La Zenia, villa's La Zenia, Costa Blanca Zuid, Spanje",
"title":"Eigendom te koop La Zenia, Costa Blanca Zuid",
"h1":"Eigendom te koop La Zenia",
"pagename_en":"la-zenia-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-La-Zenia-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-La-ZeniaCosta-Blanca-Sud-",
"pagename_de":"la-zenia-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Los Balcones",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'Los Balcones' ORDER BY intprice ASC",
"description":"Eigendom te koop in Los Balcones, Costa Blanca Zuid",
"keywords":"Appartementen Los Balcones, geschakelde woningen Los Balcones, villa's Los Balcones, Costa Blanca Zuid, Spanje",
"title":"Eigendom te koop Los Balcones, Costa Blanca Zuid",
"h1":"Eigendom te koop Los Balcones",
"pagename_en":"los-balcones-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Los-Balcones-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Los-Balcones-Costa-Blanca-Sud-",
"pagename_de":"los-balcones-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Punta Prima",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'Punta Prima' ORDER BY intprice ASC",
"description":"Eigendom te koop in Punta Prima, Costa Blanca Zuid",
"keywords":"Appartementen Punta Prima, Costa Blanca Zuid, Spanje",
"title":"Eigendom te koop Punta Prima, Costa Blanca Zuid",
"h1":"Eigendom te koop in Punta Prima",
"pagename_en":"punta-prima-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Punta-Prima-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Punta-Prima-Costa-Blanca-Sud-",
"pagename_de":"punta-prima-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Alameda",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail LIKE ('%Alameda%') ORDER BY intprice ASC",
"description":"Eigendom te koop in Alameda, Costa Blanca Zuid",
"keywords":"Appartementen Alameda, geschakelde woningen Alameda, villa's Alameda, Costa Blanca Zuid, Spanje",
"title":"Eigendom te koop Alameda, Costa Blanca Zuid",
"h1":"Eigendom te koop Alameda",
"pagename_en":"alameda-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Alameda-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Alameda-Costa-Blanca-Sud-",
"pagename_de":"alameda-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Campoamor",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail LIKE ('%Campoamor%') ORDER BY intprice ASC",
"description":"Eigendom te koop in Campoamor, Costa Blanca Zuid",
"keywords":"Appartementen Campoamor, geschakelde woningen Campoamor, villa's Campoamor, Costa Blanca Zuid, Spanje",
"title":"Eigendom te koop Campoamor, Costa Blanca Zuid",
"h1":"Eigendom te koop Campoamor",
"pagename_en":"campoamor-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Campoamor-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Campoamor-Costa-Blanca-Sud-",
"pagename_de":"campoamor-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Las Filipinas",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'Las Filipinas' ORDER BY intprice ASC",
"description":"Eigendom te koop in Las Filipinas, Costa Blanca Zuid",
"keywords":"Appartementen Las Filipinas, geschakelde woningen Las Filipinas, villa's Las Filipinas, Costa Blanca Zuid, Spanje",
"title":"Eigendom te koop Las Filipinas, Costa Blanca Zuid",
"h1":"Eigendom te koop Las Filipinas",
"pagename_en":"las-filipinas-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Las-Filipinas-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Las-Filipinas-Costa-Blanca-Sud-",
"pagename_de":"las-filipinas-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Los Dolses",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'Los Dolses' ORDER BY intprice ASC",
"description":"Eigendom te koop in Los Dolses, Costa Blanca Zuid",
"keywords":"Appartementen Los Dolses, geschakelde woningen Los Dolses, villa's Los Dolses, Costa Blanca Zuid, Spanje",
"title":"Eigendom te koop Los Dolses, Costa Blanca Zuid",
"h1":"Eigendom te koop Los Dolses",
"pagename_en":"los-dolses-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Los-Dolses-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Los-Dolses-Costa-Blanca-Sud-",
"pagename_de":"los-dolses-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Las Ramblas",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'Las Ramblas' ORDER BY intprice ASC",
"description":"Eigendom te koop in Las Ramblas, Costa Blanca Zuid",
"keywords":"Appartementen Las Ramblas, geschakelde woningen Las Ramblas, villa's Las Ramblas, Costa Blanca Zuid, Spanje",
"title":"Eigendom te koop Las Ramblas, Costa Blanca Zuid",
"h1":"Eigendom te koop in Las Ramblas",
"pagename_en":"las-ramblas-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Las-Ramblas-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Las-Ramblas-Costa-Blanca-Sud-",
"pagename_de":"las-ramblas-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Rio Mar",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'Rio Mar' ORDER BY intprice ASC",
"description":"Eigendom te koop in Rio Mar, Costa Blanca Zuid",
"keywords":"Appartementen Rio Mar, geschakelde woningen Rio Mar, villa's Rio Mar, Costa Blanca Zuid, Spanje",
"title":"Eigendom te koop Rio Mar, Costa Blanca Zuid",
"h1":"Eigendom te koop Rio Mar",
"pagename_en":"rio-mar-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Rio-Mar-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Rio-Mar-Costa-Blanca-Sud-",
"pagename_de":"rio-mar-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Torrevieja",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strtown = 'Torrevieja' ORDER BY intprice ASC",
"description":"Eigendom te koop in Torrevieja, Costa Blanca Zuid",
"keywords":"Appartementen Torrevieja, geschakelde woningen Torrevieja, villa's Torrevieja, Costa Blanca Zuid, Spanje",
"title":"Eigendom te koop Torrevieja, Costa Blanca Zuid",
"h1":"Eigendom te koop Torrevieja",
"pagename_en":"torrevieja-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Torrevieja-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Torrevieja-Costa-Blanca-Sud-",
"pagename_de":"torrevieja-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Dream Hills",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'Dream Hills' ORDER BY intprice ASC",
"description":"Eigendom te koop in Dream Hills, Costa Blanca Zuid",
"keywords":"Appartementen Dream Hills, geschakelde woningen Dream Hills, villa's Dream Hills, Costa Blanca Zuid, Spanje",
"title":"Eigendom te koop Dream Hills, Costa Blanca Zuid",
"h1":"Eigendom te koop Dream Hills",
"pagename_en":"dream-hills-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Dream-Hills-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Dream-Hills-Costa-Blanca-Sud-",
"pagename_de":"dream-hills-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Algorfa",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'Algorfa' ORDER BY intprice ASC",
"description":"Eigendom te koop in Algorfa, Costa Blanca Zuid",
"keywords":"Appartementen Algorfa, geschakelde woningen Algorfa, villa's Algorfa, Costa Blanca Zuid, Spanje",
"title":"Eigendom te koop Algorfa, Costa Blanca Zuid",
"h1":"Eigendom te koop Algorfa",
"pagename_en":"algorfa-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Algorfa-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Algorfa-Costa-Blanca-Sud-",
"pagename_de":"algorfa-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"La Mata",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'La Mata' ORDER BY intprice ASC",
"description":"Eigendom te koop in La Mata, Costa Blanca Zuid",
"keywords":"Appartementen La Mata, geschakelde woningen La Mata, villa's La Mata, Costa Blanca Zuid, Spanje",
"title":"Eigendom te koop La Mata, Costa Blanca Zuid",
"h1":"Eigendom te koop La Mata",
"pagename_en":"la-mata-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-La-Mata-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-La-Mata-Costa-Blanca-Sud-",
"pagename_de":"la-mata-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"La Torreta",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'La Torreta' ORDER BY intprice ASC",
"description":"Eigendom te koop in La Torreta, Costa Blanca Zuid",
"keywords":"Appartementen La Torreta, geschakelde woningen La Torreta, villa's La Torreta, Costa Blanca Zuid, Spanje",
"title":"Eigendom te koop La Torreta, Costa Blanca Zuid",
"h1":"Eigendom te koop La Torreta",
"pagename_en":"la-torreta-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-La-Torreta-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-La-Torreta-Costa-Blanca-Sud-",
"pagename_de":"la-torreta-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Los Altos",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'Los Altos' ORDER BY intprice ASC",
"description":"Eigendom te koop in Los Altos, Costa Blanca Zuid",
"keywords":"Appartementen Los Altos, geschakelde woningen Los Altos, villa's Los Altos, Costa Blanca Zuid, Spanje",
"title":"Eigendom te koop Los Altos, Costa Blanca Zuid",
"h1":"Eigendom te koop Los Altos",
"pagename_en":"los-altos-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Los-Altos-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Los-Altos-Costa-Blanca-Sud-",
"pagename_de":"los-altos-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Mar Azul",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'Mar Azul' ORDER BY intprice ASC",
"description":"Eigendom te koop in Mar Azul, Costa Blanca Zuid",
"keywords":"Appartementen Mar Azul, geschakelde woningen Mar Azul, villa's Mar Azul, Costa Blanca Zuid, Spanje",
"title":"Eigendom te koop Mar Azul, Costa Blanca Zuid",
"h1":"Eigendom te koop Mar Azul",
"pagename_en":"mar-azul-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Mar-Azul-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Mar-Azul-Costa-Blanca-Sud-",
"pagename_de":"mar-azul-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Miraflores",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'Miraflores' ORDER BY intprice ASC",
"description":"Eigendom te koop in Miraflores, Costa Blanca Zuid",
"keywords":"Appartementen Miraflores, geschakelde woningen Miraflores, villa's Miraflores, Costa Blanca Zuid, Spanje",
"title":"Eigendom te koop Miraflores, Costa Blanca Zuid",
"h1":"Eigendom te koop Miraflores",
"pagename_en":"miraflores-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Miraflores-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Miraflores-Costa-Blanca-Sud-",
"pagename_de":"miraflores-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Rocio del Mar",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'Rocio del Mar' ORDER BY intprice ASC",
"description":"Eigendom te koop in Rocio del Mar, Costa Blanca Zuid",
"keywords":"Appartementen Rocio del Mar, geschakelde woningen Rocio del Mar, villa's Rocio del Mar, Costa Blanca Zuid, Spanje",
"title":"Eigendom te koop Rocio del Mar, Costa Blanca Zuid",
"h1":"Eigendom te koop Rocio del Mar",
"pagename_en":"rocio-del-mar-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Rocio-del-Mar-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Rocio-del-Mar-Costa-Blanca-Sud-",
"pagename_de":"rocio-del-mar-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"La Manga",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail Like 'La Manga%' ORDER BY intprice ASC",
"description":"Eigendom te koop in La Manga, Costa Blanca Zuid",
"keywords":"Appartementen La Manga, geschakelde woningen La Manga, villa's La Manga, Costa Blanca Zuid, Spanje",
"title":"Eigendom te koop La Manga, Murcia",
"h1":"Eigendom te koop in La Manga del Mar Menor",
"pagename_en":"la-manga-property-murcia-",
"pagename_nl":"Eigendom-te-koop-in-La-Manga-del-Mar-Menor-",
"pagename_fr":"Propriete-a-vendre-a-La-Manga-del-Mar-Menor-",
"pagename_de":"la-manga-Immobilien-murcia-"
},
{
"rubrun":"Los Alcazares",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strtown = 'Los Alcazares' ORDER BY intprice ASC",
"description":"Eigendom te koop in Los Alcazares, Costa Blanca Zuid",
"keywords":"Appartementen Los Alcazares, geschakelde woningen Los Alcazares, villa's Los Alcazares, Costa Blanca Zuid, Spanje",
"title":"Eigendom te koop Los Alcazares, Murcia",
"h1":"Eigendom te koop Los Alcazares",
"pagename_en":"los-alcazares-property-murcia-",
"pagename_nl":"Eigendom-te-koop-in-Los-Alcazares-murcia-",
"pagename_fr":"Propriete-a-vendre-a-Los-Alcazares-Murcia-",
"pagename_de":"los-alcazares-Immobilien-murcia-"
}
]
