#!/usr/bin/python
# -*- coding: utf-8 -*-
rubruns=[
{
"rubrun":"All-props",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND blnrental = 0 ORDER BY intprice ASC",
"description":"Villas, appartements, maisons mitoyennes et fincas à vendre à Villamartin, Playa Flamenca, Cabo Roig, Los Altos, Los Balcones, Guardamar del Segura, Ciudad Quesada, Torrevieja et Costa Blanca Sud, Espagne",
"keywords":"Villas, appartements, maisons mitoyennes et fincas à Villamartin, Playa Flamenca, Cabo Roig, Guardamar del Segura et Ciudad Quesada",
"title":"Villas, appartements, maisons mitoyennes et fincas à vendre à Playa Flamenca, Cabo Roig, Guardamar del Segura et Ciudad Quesada, Costa Blanca Sud",
"h1":"Propriétét à vendre à Villamartin, Cabo Roig, Torrevieja, Playa Flamenca et Orihuela Costa, Espagne",
"pagename_en":"villas-apartments-townhouses-and-fincas-for-sale-",
"pagename_nl":"villas-appartementen-geschakelde-woningen-en-fincas-te-koop-",
"pagename_fr":"Villas-appartements-maisons-mitoyennes-et-fincas-a-vendre-",
"pagename_de":"villas-Ferienwohnungen-Stadthauser-und-fincas-zu-verkaufen-"
},
{
"rubrun":"Up to 100000",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND blnrental = 0 AND intprice <= 100000 ORDER BY intprice ASC",
"description":"Villas, appartements, maisons mitoyennes et fincas jusqu à 100 000 euros",
"keywords":"Villas à bas prix, appartements à bas prix, maisons mitoyennes à bas prix Costa Blanca",
"title":"Propriété à Costa Blanca jusqu'à 100 000 euros",
"h1":"Propriété à vendre à Villamartin, Cabo Roig, Torrevieja, Playa Flamenca, Costa Blanca Sud jusqu'à 100 000 euros",
"pagename_en":"costa-blanca-property-for-less-than-100000-",
"pagename_nl":"Eigendom-in-de-Costa-Blanca-tot-100000-euro-",
"pagename_fr":"Propriete-a-Costa-Blanca-jusqu-a-100000-euro-",
"pagename_de":"costa-blanca-Immobilien-fur-weniger-als-100000-"
},
{
"rubrun":"101000-200000",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND blnrental = 0 AND intprice >= 101000  AND intprice <= 200000 ORDER BY intprice ASC",
"description":"Villas, appartements, maisons mitoyennes et fincas de 100 000 euros à 200 000 euros",
"keywords":"Villas à moyen prix, appartements à moyen prix, appartements à bas prix, et maisons mitoyennes Costa Blanca",
"title":"Propriété à Costa Blanca de 100 000 euros à 200 000 euros",
"h1":"Propriété à vendre à Villamartin, Cabo Roig, Torrevieja, Playa Flamenca, Costa Blanca Sud de 100 000 euros à 200 000 euros",
"pagename_en":"costa-blanca-property-from-100000-to-200000-",
"pagename_nl":"Eigendom-aan-de-Costa-Blanca-van-100000-tot-200000-euro-",
"pagename_fr":"Propriete-a-Costa-Blanca-de-100000-euro-a-200000-euro-",
"pagename_de":"costa-blanca-Immobilien-von-100000-bis-200000-"
},
{
"rubrun":"201000-300000",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND blnrental = 0 AND intprice >= 201000  AND intprice <= 300000 ORDER BY intprice ASC",
"description":"Villas, appartements, maisons mitoyennes et fincas de 200 000 euros à 300 000 euros",
"keywords":"Villas populaires, appartements agréables, et maisons magnifiques Costa Blanca",
"title":"Propriété à Costa Blanca de 200 000 euros à 300 000 euros",
"h1":"Propriété à vendre à Villamartin, Cabo Roig, Torrevieja, Playa Flamenca, Costa Blanca Sud de 200 000 euros à 300 000 euros",
"pagename_en":"costa-blanca-property-from-200000-to-300000-",
"pagename_nl":"Eigendom-aan-de-Costa-Blanca-van-200000-tot-300000-euro-",
"pagename_fr":"Propriete-a-Costa-Blanca-de-200000-euro-a-300000-euro-",
"pagename_de":"costa-blanca-Immobilien-von-200000-bis-300000-"
},
{
"rubrun":"301000-400000",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND blnrental = 0 AND intprice >= 301000  AND intprice <= 400000 ORDER BY intprice ASC",
"description":"Villas, appartements, maisons mitoyennes et fincas de 300 000 euros à 400 000 euros",
"keywords":"Villas magnifiques, appartements de luxe, et maisons pour retraités Costa Blanca",
"title":"Propriété à Costa Blanca de 300 000 euros à 400 000 euros",
"h1":"Propriété à vendre à Villamartin, Cabo Roig, Torrevieja, Playa Flamenca, Costa Blanca Sud de 300 000 euros à 400 000 euros",
"pagename_en":"costa-blanca-property-from-300000-to-400000-",
"pagename_nl":"Eigendom-aan-de-Costa-Blanca-van-300000-tot-400000-euro-",
"pagename_fr":"Propriete-a-Costa-Blanca-de-300000-euro-a-400000-euro-",
"pagename_de":"costa-blanca-Immobilien-von-300000-bis-400000-"
},
{
"rubrun":"401000-500000",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND blnrental = 0 AND intprice >= 401000  AND intprice <= 500000 ORDER BY intprice ASC",
"description":"Villas, appartements, maisons mitoyennes et fincas de 400 000 euros à 500 000 euros",
"keywords":"Appartements et villas bien équipées, maisons confortables Costa Blanca",
"title":"Propriété à Costa Blanca de 400 000 euros à 500 000 euros",
"h1":"Propriété à vendre à Villamartin, Cabo Roig, Torrevieja, Playa Flamenca, Costa Blanca Sud de 400 000 euros à 500 000 euros",
"pagename_en":"costa-blanca-property-from-400000-to-500000-",
"pagename_nl":"Eigendom-aan-de-Costa-Blanca-van-400000-tot-500000-euro-",
"pagename_fr":"Propriete-a-Costa-Blanca-de-400000-euro-a-500000-euro-",
"pagename_de":"costa-blanca-Immobilien-von-400000-bis-500000-"
},
{
"rubrun":"501000-600000",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND blnrental = 0 AND intprice >= 501000  AND intprice <= 600000 ORDER BY intprice ASC",
"description":"Villas, appartements, maisons mitoyennes et fincas de 500 000 euros à 600 000 euros",
"keywords":"Maisons Costa Blanca,  villas, appartements, maisons sur le golf resort, propriété Costa Blanca Sud, Espagne",
"title":"Propriété à Costa Blanca de 500 000 euros à 600 000 euros",
"h1":"Propriété à vendre à Villamartin, Cabo Roig, Campoamor, Playa Flamenca, Costa Blanca Sud de 500 000 euros à 600 000 euros",
"pagename_en":"costa-blanca-property-from-500000-to-600000-",
"pagename_nl":"Eigendom-aan-de-Costa-Blanca-van-500000-tot-600000-euro-",
"pagename_fr":"Propriete-a-Costa-Blanca-de-500000-euro-a-600000-euro-",
"pagename_de":"costa-blanca-Immobilien-von-500000-bis-600000-"
},
{
"rubrun":"601000-700000",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND blnrental = 0 AND intprice >= 601000  AND intprice <= 700000 ORDER BY intprice ASC",
"description":"Villas, appartements, maisons mitoyennes et fincas de 600 000 euros à 700 000 euros",
"keywords":"Maisons Costa Blanca, Villas, Appartements, Maisons sur le golf resort, Propriété Costa Blanca Sud, Espagne",
"title":"Propriété à Costa Blanca de 600 000 euros à 700 000 euros",
"h1":"Propriété à vendre à Villamartin, Cabo Roig, Campoamor, Playa Flamenca, Costa Blanca Sud de 600 000 euros à 700 000 euros",
"pagename_en":"costa-blanca-property-from-600000-to-700000-",
"pagename_nl":"Eigendom-aan-de-Costa-Blanca-van-600000-tot-700000-euro-",
"pagename_fr":"Propriete-a-Costa-Blanca-de-600000-euro-a-700000-euro-",
"pagename_de":"costa-blanca-Immobilien-von-600000-bis-700000-"
},
{
"rubrun":"701000-800000",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND blnrental = 0 AND intprice >= 701000  AND intprice <= 800000 ORDER BY intprice ASC",
"description":"Villas, appartements, maisons mitoyennes et fincas de 700 000 euros à 800 000 euros",
"keywords":"Maisons confortables Costa Blanca, villas, appartements, maisons sur le golf resort, propriété Costa Blanca Sud, Espagne",
"title":"Propriété à Costa Blanca de 700 000 euros à 800 000 euros",
"h1":"Propriété à vendre à Villamartin, Cabo Roig, Campoamor, Playa Flamenca, Costa Blanca Sud de 700 000 euros à 800 000 euros",
"pagename_en":"costa-blanca-property-from-700000-to-800000-",
"pagename_nl":"Eigendom-aan-de-Costa-Blanca-van-700000-tot-800000-euro-",
"pagename_fr":"Propriete-a-Costa-Blanca-de-700000-euro-a-800000-euro-",
"pagename_de":"costa-blanca-Immobilien-von-700000-bis-800000-"
},
{
"rubrun":"801000-900000",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND blnrental = 0 AND intprice >= 801000  AND intprice <= 900000 ORDER BY intprice ASC",
"description":"Villas, appartements, maisons mitoyennes et fincas de 800 000 euros à 900 000 euros",
"keywords":"Maisons de luxe Costa Blanca, villas, appartements, maisons sur le golf resort, propriété Costa Blanca Sud, Espagne",
"title":"Propriété à Costa Blanca de 800 000 euros à 900 000 euros",
"h1":"Propriété à vendre à Villamartin, Cabo Roig, Campoamor, Playa Flamenca, Costa Blanca Sud de 800 000 euros à 900 000 euros",
"pagename_en":"costa-blanca-property-from-800000-to-900000-",
"pagename_nl":"Eigendom-aan-de-Costa-Blanca-van-800000-tot-900000-euro-",
"pagename_fr":"Propriete-a-Costa-Blanca-de-800000-euro-a-900000-euro-",
"pagename_de":"costa-blanca-Immobilien-von-800000-bis-900000-"
},
{
"rubrun":"more than 900000",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND blnrental = 0 AND intprice > 900000 ORDER BY intprice ASC",
"description":"Villas, appartements, maisons mitoyennes et fincas à partir de 900 000 euros",
"keywords":"Maisons uniques Costa Blanca, villas, appartements, maisons sur le golf resort, propriété Costa Blanca Sud, Espagne",
"title":"Propriétés uniques à Costa Blanca à partir de 900 000 euros",
"h1":"Propriété à vendre à Villamartin, Cabo Roig, Campoamor, Playa Flamenca, Costa Blanca Sud à partir de 900 000 euros",
"pagename_en":"costa-blanca-property-from-900000-",
"pagename_nl":"Eigendom-aan-de-Costa-Blanca-vanaf-900000-euro-",
"pagename_fr":"Propriete-a-Costa-Blanca-a-partir-de-900000-euro-",
"pagename_de":"costa-blanca-Immobilien-von-900000-"
},
{
"rubrun":"apartments",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND strpropertytype = 'Apartment' ORDER BY intprice ASC",
"description":"Appartements à vendre à Costa Blanca Sud",
"keywords":"appartement espagnol, appartement Costa Blanca Sud, appartement Espagne, appartement plage, appartement golf resort appartement de luxe",
"title":"Appartements à vendre Costa Blanca Sud",
"h1":"Appartements à Villamartin, Cabo Roig, Campoamor, Playa Flamenca, Costa Blanca Sud",
"pagename_en":"apartments-for-sale-costa-blanca-south-",
"pagename_nl":"Appartement-te-koop-costa-blanca-zuid-",
"pagename_fr":"Appartements-a-vendre-Costa-Blanca-Sud-",
"pagename_de":"Ferienwohnungen-zu-verkaufen-costa-blanca-sud-"
},
{
"rubrun":"Commercial",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND (strpropertytype IN ('Bar','Restaurant','Business','Commercial','Hotel')) ORDER BY intprice ASC",
"description":"Bâtiments commerciaux et bureaux à Costa Blanca Sud, cafés, restaurants, hôtels",
"keywords":"bâtiments commerciaux Costa Blanca, bureaux Costa Blanca, cafés, restaurants, hôtels",
"title":"Bâtiments commerciaux à Costa Blanca ",
"h1":"Bâtiments commerciaux Costa Blanca Sud",
"pagename_en":"costa-blanca-commercial-property-",
"pagename_nl":"Commerciele-panden-Costa-Blanca-Zuid-",
"pagename_fr":"Batiments-commerciaux-Costa-Blanca-Sud-",
"pagename_de":"costa-blanca-Gewerbeimmobilien-"
},
{
"rubrun":"Long Term Rentals",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND blnrental = 1 AND strFrequency = 'month' ORDER BY intprice ASC",
"description":"Propriété à louer pour long terme à Costa Blanca Sud",
"keywords":"louer Costa Blanca, louer pour long terme, louer long terme ",
"title":"Maisons à Costa Blanca à louer pour long terme",
"h1":"Propriété à louer pour long terme Costa Blanca Sud",
"pagename_en":"costa-blanca-long-term-rental-property-",
"pagename_nl":"Eigendom-te-huur-voor-lange-termijn-costa-blanca-zuid-",
"pagename_fr":"Propriete-a-louer-pour-long-terme-Costa-Blanca-Sud-",
"pagename_de":"costa-blanca-Langfristige-Vermietungen-"
},
{
"rubrun":"Holiday Rentals",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND blnrental = 1 AND strFrequency = 'week' ORDER BY intprice ASC",
"description":"Maisons de vacances à louer à Costa Blanca Sud",
"keywords":"Louer Costa Blanca, louer pour vacances, louer vacances",
"title":"Maisons de vacances à louer à Costa Blanca",
"h1":"Maisons de vacances à louer Costa Blanca Sud",
"pagename_en":"costa-blanca-holiday-rental-property-",
"pagename_nl":"Vakantieverhuur-costa-blanca-zuid-",
"pagename_fr":"Maisons-de-vacances-a-louer-Costa-Blanca-Sud-",
"pagename_de":"costa-blanca-FerienunterkuNfte-"
},
{
"rubrun":"Key Ready",
"query":"Select * FROM mghprops WHERE blndisplay = 1 AND blnoffplan = 1 ORDER BY intprice ASC",
"description":"Propriété Costa Blanca Sud. Clé sur porte et nouvelles constructions sur la plage et à l' intérieur",
"keywords":"Appartements clé sur porte, maisons mitoyennes clé sur porte, villas clé sur porte, Costa Blanca Sud",
"title":"Maisons clé sur porte Costa Blanca Sud",
"h1":"Propriétés clé sur porte à Villamartin, Cabo Roig, Campoamor, Playa Flamenca, Costa Blanca Sud",
"pagename_en":"key-ready-homes-costa-blanca-south-",
"pagename_nl":"nieuwbouw-costa-blanca-zuid-",
"pagename_fr":"nouvelles-constructions-Costa-Blanca-Sud-",
"pagename_de":"neue-Hauser-costa-blanca-sud-"
},
{
"rubrun":"penthouse",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnpenthouse = 1 ORDER BY intprice ASC",
"description":"Appartements à deux étages à Costa Blanca Sud",
"keywords":"appartements à deux étages, Costa Blanca Sud, Espagne, appartements deux étages, Costa Blanca Sud, Espagne",
"title":"Appartements à deux étages à Costa Blanca Sud",
"h1":"Appartements à deux étages à vendre à Costa Blanca Sud",
"pagename_en":"penthouse-apartments-south-costa-blanca-",
"pagename_nl":"Penthouse-dakappartement-costa-blanca-zuid-",
"pagename_fr":"Appartements-a-deux-etages-Costa-Blanca-Sud-",
"pagename_de":"penthouse-Ferienwohnungen-costa-blanca-sud-"
},
{
"rubrun":"beach",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnbeach = 1 ORDER BY intprice ASC",
"description":"Propriété à vendre sur la plage à Costa Blanca Sud",
"keywords":"appartements plage, maisons mitoyennes plage, villas plage, Costa Blanca Sud, Espagne.",
"title":"Propriété sur la plage, Costa Blanca Sud",
"h1":"Propriété à vendre sur la plage, Costa Blanca Sud, Espagne",
"pagename_en":"beach-property-south-costa-blanca-",
"pagename_nl":"Eigendom-aan-het-strand-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-sur-la-plage-Costa-Blanca-Sud-",
"pagename_de":"Strand-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"golf",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blngolf = 1 ORDER BY intprice ASC",
"description":"Propriété à vendre sur le golf resort à Costa Blanca Sud",
"keywords":"appartements golf resort, maisons mitoyennes golf resort, villas golf resort, Costa Blanca Sud, Espagne",
"title":"Propriété à vendre sur le golf resort à Costa Blanca Sud",
"h1":"Propriété à vendre sur le golf resort - Costa Blanca Sud, Espagne",
"pagename_en":"golf-property-south-costa-blanca-",
"pagename_nl":"Eigendom-aan-de-golf-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-sur-le-golf-resort-Costa-Blanca-Sud-",
"pagename_de":"golf-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"townhouses",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND strpropertytype = 'Townhouse' ORDER BY intprice ASC",
"description":"Maisons mitoyennes à vendre à Costa Blanca Sud",
"keywords":"maison mitoyenne espagnole, maison mitoyenne Costa Blanca, maison mitoyenne Espagne, maison mitoyenne plage, maison mitoyenne golf resort, maison mitoyenne de luxe",
"title":"Maisons mitoyennes à vendre Costa Blanca Sud",
"h1":"Maisons mitoyennes à Villamartin, Cabo Roig, Campoamor, Playa Flamenca, Costa Blanca Sud",
"pagename_en":"townhouses-for-sale-costa-blanca-south-",
"pagename_nl":"Geschakelde-woningen-Costa-Blanca-Zuid-",
"pagename_fr":"Maisons-mitoyennes-Costa-Blanca-Sud-",
"pagename_de":"Stadthauser-zu-verkaufen-costa-blanca-sud-"
},
{
"rubrun":"quadhouses",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND strpropertytype = 'Quadhouse' ORDER BY intprice ASC",
"description":"Maisons mitoyennes (quatre sous un même toit) à vendre à Costa Blanca Sud",
"keywords":"Maison mitoyenne (quatre sous un même toit) espagnole,  maison mitoyenne (quatre sous un même toit) Costa Blanca, maison mitoyenne (quatre sous un même toit) Espagne, maison mitoyenne (quatre sous un même toit) plage, maison mitoyenne (quatre sous un même toit) golf resort, maison mitoyenne (quatre sous un même toit) spacieuse",
"title":"Maisons mitoyennes (quatre sous un même toit) à vendre Costa Blanca Sud",
"h1":"Maisons mitoyennes (quatre sous un même toit) à Villamartin, Cabo Roig, Campoamor, Playa Flamenca, Costa Blanca Sud",
"pagename_en":"quadhouses-for-sale-costa-blanca-south-",
"pagename_nl":"Kwadranthuizen-Costa-Blanca-Zuid-",
"pagename_fr":"Maisons-mitoyennes-quatre-Costa-Blanca-Sud-",
"pagename_de":"quadhaus-zu-verkaufen-costa-blanca-sud-"
},
{
"rubrun":"Semidetached Villa",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND strpropertytype = 'Semidetached Villa' ORDER BY intprice ASC",
"description":"Villas jumelées à vendre à Costa Blanca Sud",
"keywords":"villa jumelée espagnole, villa jumelée Costa Blanca, villa jumelée Espagne, villa jumelée plage, villa jumelée golf resort, villa jumelée spacieuse",
"title":"Villas jumelées à vendre Costa Blanca Sud",
"h1":"Villas jumelées à Villamartin, Cabo Roig, Campoamor, Playa Flamenca, Costa Blanca Sud",
"pagename_en":"semidetached-villas-for-sale-costa-blanca-south-",
"pagename_nl":"Half-vrijstaande-villas-Costa-Blanca-Zuid-",
"pagename_fr":"Villas-jumelees-Costa-Blanca-Sud-",
"pagename_de":"Doppelhaus-villa-zu-verkaufen-costa-blanca-sud-"
},
{
"rubrun":"Villa",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND (strpropertytype = 'Villa' OR strpropertytype = 'Detached Villa') ORDER BY intprice ASC",
"description":"Villas à vendre à Costa Blanca Sud",
"keywords":"villa espagnole, villa Costa Blanca, villa Espagne, villa plage, villa golf resort, villa spacieuse",
"title":"Villas à vendre Costa Blanca Sud",
"h1":"Villas à Villamartin, Cabo Roig, Campoamor, Playa Flamenca, Costa Blanca Sud",
"pagename_en":"villas-for-sale-costa-blanca-south-",
"pagename_nl":"Villas-Costa-Blanca-Zuid-",
"pagename_fr":"Villas-Costa-Blanca-Sud-",
"pagename_de":"villas-zu-verkaufen-costa-blanca-south-"
},
{
"rubrun":"fincas",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnfinca = 1 ORDER BY intprice ASC",
"description":"Fincas et maisons de campagne à vendre à Costa Blanca Sud",
"keywords":"Fincas et maisons de campagne espagnoles, fincas et maisons de campagne Costa Blanca, fincas et maisons de campagne Espagne, fincas et maisons de campagne spacieuses",
"title":"Fincas et maisons de campagne à vendre Costa Blanca Sud",
"h1":"Fincas et maisons de campagne Costa Blanca Sud",
"pagename_en":"fincas-and-country-homes-for-sale-costa-blanca-south-",
"pagename_nl":"Fincas-en-landhuizen-Costa-Blanca-Zuid-",
"pagename_fr":"Fincas-et-maisons-de-campagne-Costa-Blanca-Sud-",
"pagename_de":"Landliche-Landhauser-zu-verkaufen-costa-blanca-south-"
},
{
"rubrun":"Luxury",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND blnluxury = 1 ORDER BY intprice ASC",
"description":"Propriété de luxe à vendre à Costa Blanca Sud",
"keywords":"appartements de luxe, maisons mitoyennes de luxe, villas de luxe, Costa Blanca Sud, Espagne",
"title":"Propriété de luxe à vendre Costa Blanca Sud",
"h1":"Propriété de luxe à vendre à Villamartin, Cabo Roig, Campoamor, Playa Flamenca, Costa Blanca Sud",
"pagename_en":"luxury-property-south-costa-blanca-",
"pagename_nl":"Luxe-eigendom-te-koop-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-de-luxe-a-vendre-Costa-Blanca-Sud-",
"pagename_de":"Luxus-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Orihuela Costa",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strtown = 'Orihuela Costa' ORDER BY intprice ASC",
"description":"Propriété à vendre à Orihuela Costa, Costa Blanca Sud",
"keywords":"Appartements Orihuela Costa, maisons mitoyennes Orihuela Costa, villas Orihuela Costa, Costa Blanca Sud, Espagne",
"title":"Propriété à vendre Orihuela Costa, Costa Blanca Sud",
"h1":"Propriété à vendre à Orihuela Costa, Villamartin, Cabo Roig, Campoamor, Playa Flamenca",
"pagename_en":"orihuela-costa-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Orihuela-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Orihuela-Costa-Costa-Blanca-Sud-",
"pagename_de":"orihuela-costa-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Villamartin",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail IN('Villamartin','Villamartin Golf') ORDER BY intprice ASC",
"description":"Propriété à vendre à Villamartin, Costa Blanca Sud",
"keywords":"Appartements Villamartin, maisons mitoyennes Villamartin, villas Villamartin, Costa Blanca Sud, Espagne",
"title":"Propriété à vendre Villamartin, Costa Blanca Sud",
"h1":"Propriété à vendre Villamartin",
"pagename_en":"villamartin-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Villamartin-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Villamartin-Costa-Blanca-Sud-",
"pagename_de":"villamartin-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Playa Flamenca",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail ='Playa Flamenca' ORDER BY intprice ASC",
"description":"Propriété à vendre à Playa Flamenca, Costa Blanca Sud",
"keywords":"Appartements Playa Flamenca, maisons mitoyennes Playa Flamenca, villas Playa Flamenca, Costa Blanca Sud, Espagne",
"title":"Propriété à vendre Playa Flamenca, Costa Blanca Sud",
"h1":"Propriété à vendre Playa Flamenca",
"pagename_en":"playa-flamenca-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Playa-Flamenca-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Playa-Flamenca-Costa-Blanca-Sud-",
"pagename_de":"playa-flamenca-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Cabo Roig",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail ='Cabo Roig' ORDER BY intprice ASC",
"description":"Propriété à vendre à Cabo Roig, Costa Blanca Sud",
"keywords":"Appartements Cabo Roig, maisons mitoyennes Cabo Roig, villas Cabo Roig, Costa Blanca Sud, Espagne",
"title":"Propriété à vendre Cabo Roig, Costa Blanca Sud",
"h1":"Propriété à vendre Cabo Roig",
"pagename_en":"cabo-roig-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Cabo-Roig-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Cabo-Roig-Costa-Blanca-Sud-",
"pagename_de":"cabo-roig-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Guardamar del Segura",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail IN('Guardamar','Guardamar del Segura','Guardamar Campo') ORDER BY intprice ASC",
"description":"Propriété à vendre à Guardamar del Segura, Costa Blanca Sud",
"keywords":"Appartements Guardamar del Segura, maisons mitoyennes Guardamar del Segura, villas Guardamar del Segura, Costa Blanca Sud, Espagne",
"title":"Propriété à vendre Guardamar del Segura, Costa Blanca Sud",
"h1":"Propriété à vendre Guardamar del Segura",
"pagename_en":"guardamar-del-segura-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Guardamar-del-Segura-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Guardamar-del-Segura-Costa-Blanca-Sud-",
"pagename_de":"guardamar-del-segura-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Quesada",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail LIKE('%Quesada%') ORDER BY intprice ASC",
"description":"Propriété à vendre à Quesada, Costa Blanca Sud",
"keywords":"Appartements Quesada, maisons mitoyennes Quesada, villas Quesada, Costa Blanca Sud, Espagne",
"title":"Propriété à vendre à Quesada, Costa Blanca Sud",
"h1":"Propriété à vendre à Quesada",
"pagename_en":"quesada-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Quesada-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Quesada-Costa-Blanca-Sud-",
"pagename_de":"quesada-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"La Zenia",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'La Zenia' ORDER BY intprice ASC",
"description":"Propriété à vendre à La Zenia, Costa Blanca Sud",
"keywords":"Appartements La Zenia, maisons mitoyennes La Zenia, villas La Zenia, Costa Blanca Sud, Espagne",
"title":"Propriété à vendre La Zenia, Costa Blanca Sud",
"h1":"Propriété à vendre La Zenia",
"pagename_en":"la-zenia-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-La-Zenia-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-La-ZeniaCosta-Blanca-Sud-",
"pagename_de":"la-zenia-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Los Balcones",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'Los Balcones' ORDER BY intprice ASC",
"description":"Propriété à vendre à Los Balcones, Costa Blanca Sud",
"keywords":"Appartements Los Balcones, maisons mitoyennes Los Balcones, villas Los Balcones, Costa Blanca Sud, Espagne",
"title":"Propriété à vendre Los Balcones, Costa Blanca Sud",
"h1":"Propriété à vendre Los Balcones",
"pagename_en":"los-balcones-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Los-Balcones-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Los-Balcones-Costa-Blanca-Sud-",
"pagename_de":"los-balcones-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Punta Prima",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'Punta Prima' ORDER BY intprice ASC",
"description":"Propriété à vendre à Punta Prima, Costa Blanca Sud",
"keywords":"Appartements Punta Prima, Costa Blanca Sud, Espagne",
"title":"Propriété à vendre Punta Prima, Costa Blanca Sud",
"h1":"Propriété à vendre Punta Prima",
"pagename_en":"punta-prima-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Punta-Prima-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Punta-Prima-Costa-Blanca-Sud-",
"pagename_de":"punta-prima-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Alameda",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail LIKE ('%Alameda%') ORDER BY intprice ASC",
"description":"Propriété à vendre à Alameda, Costa Blanca Sud",
"keywords":"Appartements Alameda, maisons mitoyennes Alameda, villas Alameda, Costa Blanca Sud, Espagne",
"title":"Propriété à vendre Alameda, Costa Blanca Sud",
"h1":"Propriété à vendre Alameda",
"pagename_en":"alameda-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Alameda-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Alameda-Costa-Blanca-Sud-",
"pagename_de":"alameda-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Campoamor",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail LIKE ('%Campoamor%') ORDER BY intprice ASC",
"description":"Propriété à vendre à Campoamor, Costa Blanca Sud",
"keywords":"Appartements Campoamor, maisons mitoyennes Campoamor, villas Campoamor, Costa Blanca Sud, Espagne",
"title":"Propriété à vendre Campoamor, Costa Blanca Sud",
"h1":"Propriété à vendre Campoamor",
"pagename_en":"campoamor-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Campoamor-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Campoamor-Costa-Blanca-Sud-",
"pagename_de":"campoamor-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Las Filipinas",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'Las Filipinas' ORDER BY intprice ASC",
"description":"Propriété à vendre à Las Filipinas, Costa Blanca Sud",
"keywords":"Appartements Las Filipinas, maisons mitoyennes Las Filipinas, villas Las Filipinas, Costa Blanca Sud, Espagne",
"title":"Propriété à vendre Las Filipinas, Costa Blanca Sud",
"h1":"Propriété à vendre Las Filipinas",
"pagename_en":"las-filipinas-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Las-Filipinas-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Las-Filipinas-Costa-Blanca-Sud-",
"pagename_de":"las-filipinas-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Los Dolses",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'Los Dolses' ORDER BY intprice ASC",
"description":"Propriété à vendre à Los Dolses, Costa Blanca Sud",
"keywords":"Appartements Los Dolses, maisons mitoyennes Los Dolses, villas Los Dolses, Costa Blanca Sud, Espagne",
"title":"Propriété à vendre Los Dolses, Costa Blanca Sud",
"h1":"Propriété à vendre Los Dolses",
"pagename_en":"los-dolses-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Los-Dolses-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Los-Dolses-Costa-Blanca-Sud-",
"pagename_de":"los-dolses-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Las Ramblas",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'Las Ramblas' ORDER BY intprice ASC",
"description":"Propriété à vendre à Las Ramblas, Costa Blanca Sud",
"keywords":"Appartements Las Ramblas, maisons mitoyennes Las Ramblas, villas Las Ramblas, Costa Blanca Sud, Espagne",
"title":"Propriété à vendre Las Ramblas, Costa Blanca Sud",
"h1":"Propriété à vendre Las Ramblas",
"pagename_en":"las-ramblas-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Las-Ramblas-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Las-Ramblas-Costa-Blanca-Sud-",
"pagename_de":"las-ramblas-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Rio Mar",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'Rio Mar' ORDER BY intprice ASC",
"description":"Propriété à vendre à Rio Mar, Costa Blanca Sud",
"keywords":"Appartements Rio Mar, maisons mitoyennes Rio Mar, villas Rio Mar, Costa Blanca Sud, Espagne",
"title":"Propriété à vendre Rio Mar, Costa Blanca Sud",
"h1":"Propriété à vendre Rio Mar",
"pagename_en":"rio-mar-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Rio-Mar-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Rio-Mar-Costa-Blanca-Sud-",
"pagename_de":"rio-mar-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Torrevieja",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strtown = 'Torrevieja' ORDER BY intprice ASC",
"description":"Propriété à vendre à Torrevieja, Costa Blanca Sud",
"keywords":"Appartements Torrevieja, maisons mitoyennes Torrevieja, villas Torrevieja, Costa Blanca Sud, Espagne",
"title":"Propriété à vendre Torrevieja, Costa Blanca Sud",
"h1":"Propriété à vendre Torrevieja",
"pagename_en":"torrevieja-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Torrevieja-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Torrevieja-Costa-Blanca-Sud-",
"pagename_de":"torrevieja-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Dream Hills",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'Dream Hills' ORDER BY intprice ASC",
"description":"Propriété à vendre à Dream Hills, Costa Blanca Sud",
"keywords":"Appartements Dream Hills, maisons mitoyennes Dream Hills, villas Dream Hills, Costa Blanca Sud, Espagne",
"title":"Propriété à vendre Dream Hills, Costa Blanca Sud",
"h1":"Propriété à vendre Dream Hills",
"pagename_en":"dream-hills-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Dream-Hills-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Dream-Hills-Costa-Blanca-Sud-",
"pagename_de":"dream-hills-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Algorfa",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'Algorfa' ORDER BY intprice ASC",
"description":"Propriété à vendre à Algorfa, Costa Blanca Sud",
"keywords":"Appartements Algorfa, maisons mitoyennes Algorfa, villas Algorfa, Costa Blanca Sud, Espagne",
"title":"Propriété à vendre Algorfa, Costa Blanca Sud",
"h1":"Propriété à vendre Algorfa",
"pagename_en":"algorfa-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Algorfa-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Algorfa-Costa-Blanca-Sud-",
"pagename_de":"algorfa-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"La Mata",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'La Mata' ORDER BY intprice ASC",
"description":"Propriété à vendre à La Mata, Costa Blanca Sud",
"keywords":"Appartements La Mata, maisons mitoyennes La Mata, villas La Mata, Costa Blanca Sud, Espagne",
"title":"Propriété à vendre La Mata, Costa Blanca Sud",
"h1":"Propriété à vendre La Mata",
"pagename_en":"la-mata-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-La-Mata-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-La-Mata-Costa-Blanca-Sud-",
"pagename_de":"la-mata-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"La Torreta",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'La Torreta' ORDER BY intprice ASC",
"description":"Propriété à vendre à La Torreta, Costa Blanca Sud",
"keywords":"Appartements La Torreta, maisons mitoyennes La Torreta, villas La Torreta, Costa Blanca Sud, Espagne",
"title":"Propriété à vendre La Torreta, Costa Blanca Sud",
"h1":"Propriété à vendre La Torreta",
"pagename_en":"la-torreta-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-La-Torreta-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-La-Torreta-Costa-Blanca-Sud-",
"pagename_de":"la-torreta-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Los Altos",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'Los Altos' ORDER BY intprice ASC",
"description":"Propriété à vendre à Los Altos, Costa Blanca Sud",
"keywords":"Appartements Los Altos, maisons mitoyennes Los Altos, villas Los Altos, Costa Blanca Sud, Espagne",
"title":"Propriété à vendre Los Altos, Costa Blanca Sud",
"h1":"Propriété à vendre Los Altos",
"pagename_en":"los-altos-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Los-Altos-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Los-Altos-Costa-Blanca-Sud-",
"pagename_de":"los-altos-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Mar Azul",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'Mar Azul' ORDER BY intprice ASC",
"description":"Propriété à vendre à Mar Azul, Costa Blanca Sud",
"keywords":"Appartements Mar Azul, maisons mitoyennes Mar Azul, villas Mar Azul, Costa Blanca Sud, Espagne",
"title":"Propriété à vendre Mar Azul, Costa Blanca Sud",
"h1":"Propriété à vendre Mar Azul",
"pagename_en":"mar-azul-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Mar-Azul-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Mar-Azul-Costa-Blanca-Sud-",
"pagename_de":"mar-azul-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Miraflores",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'Miraflores' ORDER BY intprice ASC",
"description":"Propriété à vendre à Miraflores, Costa Blanca Sud",
"keywords":"Appartements Miraflores, maisons mitoyennes Miraflores, villas Miraflores, Costa Blanca Sud, Espagne",
"title":"Propriété à vendre Miraflores, Costa Blanca Sud",
"h1":"Propriété à vendre Miraflores",
"pagename_en":"miraflores-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Miraflores-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Miraflores-Costa-Blanca-Sud-",
"pagename_de":"miraflores-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"Rocio del Mar",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail = 'Rocio del Mar' ORDER BY intprice ASC",
"description":"Propriété à vendre à Rocio del Mar, Costa Blanca Sud",
"keywords":"Appartements Rocio del Mar, maisons mitoyennes Rocio del Mar, villas Rocio del Mar, Costa Blanca Sud, Espagne",
"title":"Propriété à vendre Rocio del Mar, Costa Blanca Sud",
"h1":"Propriété à vendre Rocio del Mar",
"pagename_en":"rocio-del-mar-property-south-costa-blanca-",
"pagename_nl":"Eigendom-te-koop-in-Rocio-del-Mar-Costa-Blanca-Zuid-",
"pagename_fr":"Propriete-a-vendre-a-Rocio-del-Mar-Costa-Blanca-Sud-",
"pagename_de":"rocio-del-mar-Immobilien-costa-blanca-sud-"
},
{
"rubrun":"La Manga",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strlocation_detail Like 'La Manga%' ORDER BY intprice ASC",
"description":"Propriété à vendre à La Manga, Costa Blanca Sud",
"keywords":"Appartements La Manga, maisons mitoyennes La Manga, villas La Manga, Costa Blanca Sud, Espagne",
"title":"Propriété à vendre La Manga, Murcia",
"h1":"Propriété à vendre La Manga del Mar Menor",
"pagename_en":"la-manga-property-murcia-",
"pagename_nl":"Eigendom-te-koop-in-La-Manga-del-Mar-Menor-",
"pagename_fr":"Propriete-a-vendre-a-La-Manga-del-Mar-Menor-",
"pagename_de":"la-manga-Immobilien-murcia-"
},
{
"rubrun":"Los Alcazares",
"query":"SELECT * FROM  mghprops WHERE  blndisplay = 1 AND blnrental = 0 AND strtown = 'Los Alcazares' ORDER BY intprice ASC",
"description":"Propriété à vendre à Los Alcazares, Costa Blanca Sud",
"keywords":"Appartements Los Alcazares, maisons mitoyennes Los Alcazares, villas Los Alcazares, Costa Blanca Sud, Espagne",
"title":"Propriété à vendre Los Alcazares, Murcia",
"h1":"Propriété à vendre Los Alcazares",
"pagename_en":"los-alcazares-property-murcia-",
"pagename_nl":"Eigendom-te-koop-in-Los-Alcazares-murcia-",
"pagename_fr":"Propriete-a-vendre-a-Los-Alcazares-Murcia-",
"pagename_de":"los-alcazares-Immobilien-murcia-"
}
]
